In [54]:
import pandas as pd

In [27]:
file_path = "../aruba.txt"

data = []

with open(file_path, "r") as file:
    for line in file:
        parts = line.strip().split()

        date = parts[0]
        time = parts[1]
        sensor = parts[2]
        value = " ".join(parts[3:])

        data.append([date, time, sensor, value])

df = pd.DataFrame(
    data,
    columns=["date", "time", "sensor", "value"]
)

df.head(20)

          date             time sensor              value
0   2010-11-04  00:03:50.209589   M003  ON Sleeping begin
1   2010-11-04  00:03:57.399391   M003                OFF
2   2010-11-04  00:15:08.984841   T002               21.5
3   2010-11-04  00:30:19.185547   T003                 21
4   2010-11-04  00:30:19.385336   T004                 21
5   2010-11-04   00:35:22.24587   T005               20.5
6   2010-11-04  00:40:25.428962   T005                 21
7   2010-11-04  00:45:28.658171   T005               20.5
8   2010-11-04  01:05:42.269469   T001                 20
9   2010-11-04  01:15:48.936777   T002                 21
10  2010-11-04  01:30:59.100184   T003               20.5
11  2010-11-04  01:46:09.301846   T005                 20
12  2010-11-04  01:56:16.059687   T004               20.5
13  2010-11-04  02:21:32.138203   T001               19.5
14  2010-11-04  02:21:32.228625   T002               20.5
15  2010-11-04  02:32:33.351906   M003                 ON
16  2010-11-04  02:32:38.895958   M003                OFF
17  2010-11-04  02:41:45.231875   T003                 20
18  2010-11-04  02:56:55.529628   T005               19.5
19  2010-11-04  03:22:11.942589   T004                 20

,date,time,sensor,value,timestamp,sensor_type
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M
2,2010-11-04,00:15:08.984841,T002,21.5,2010-11-04 00:15:08.984841,T
3,2010-11-04,00:30:19.185547,T003,21,2010-11-04 00:30:19.185547,T
4,2010-11-04,00:30:19.385336,T004,21,2010-11-04 00:30:19.385336,T
...,...,...,...,...,...,...
1719553,2011-06-11,23:42:59.28507,T002,25.5,2011-06-11 23:42:59.285070,T
1719554,2011-06-11,23:48:02.888409,T001,23.5,2011-06-11 23:48:02.888409,T
1719555,2011-06-11,23:48:02.988798,T002,25,2011-06-11 23:48:02.988798,T
1719556,2011-06-11,23:53:06.4292,T002,25.5,2011-06-11 23:53:06.429200,T
1719557,2011-06-11,23:58:10.004834,T002,25 Sleeping end,2011-06-11 23:58:10.004834,T

In [28]:
df.shape[0]

1719558

In [29]:
df.isnull().sum()

date      0
time      0
sensor    0
value     0
dtype: int64

In [30]:
df.head(20)

          date             time sensor              value
0   2010-11-04  00:03:50.209589   M003  ON Sleeping begin
1   2010-11-04  00:03:57.399391   M003                OFF
2   2010-11-04  00:15:08.984841   T002               21.5
3   2010-11-04  00:30:19.185547   T003                 21
4   2010-11-04  00:30:19.385336   T004                 21
5   2010-11-04   00:35:22.24587   T005               20.5
6   2010-11-04  00:40:25.428962   T005                 21
7   2010-11-04  00:45:28.658171   T005               20.5
8   2010-11-04  01:05:42.269469   T001                 20
9   2010-11-04  01:15:48.936777   T002                 21
10  2010-11-04  01:30:59.100184   T003               20.5
11  2010-11-04  01:46:09.301846   T005                 20
12  2010-11-04  01:56:16.059687   T004               20.5
13  2010-11-04  02:21:32.138203   T001               19.5
14  2010-11-04  02:21:32.228625   T002               20.5
15  2010-11-04  02:32:33.351906   M003                 ON
16  2010-11-04  02:32:38.895958   M003                OFF
17  2010-11-04  02:41:45.231875   T003                 20
18  2010-11-04  02:56:55.529628   T005               19.5
19  2010-11-04  03:22:11.942589   T004                 20

In [59]:
df["timestamp"] = pd.to_datetime(
    df["date"] + " " + df["time"],
    format="mixed"
)

df.head()

,date,time,sensor,value,timestamp,sensor_type
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M
2,2010-11-04,00:15:08.984841,T002,21.5,2010-11-04 00:15:08.984841,T
3,2010-11-04,00:30:19.185547,T003,21,2010-11-04 00:30:19.185547,T
4,2010-11-04,00:30:19.385336,T004,21,2010-11-04 00:30:19.385336,T

In [32]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

Number of rows: 1719558
Number of columns: 5

In [25]:
print(df["sensor"].unique())
print(df["sensor"].nunique())

['M003' 'T002' 'T003' 'T004' 'T005' 'T001' 'M002' 'M007' 'M005' 'M004'
 'M006' 'M008' 'M020' 'M010' 'M011' 'M012' 'M013' 'M014' 'M009' 'M018'
 'M019' 'M015' 'M016' 'M017' 'M021' 'M022' 'M023' 'M001' 'M024' 'D002'
 'M031' 'D004' 'M030' 'M029' 'M028' 'D001' 'M026' 'M027' 'M025'
 'LEAVEHOME' 'ENTERHOME']
41

In [17]:
df["sensor"].value_counts()

sensor
M009         263489
M020         162204
M019         157833
M015          98320
M007          94099
M014          89186
M013          86663
M018          82256
M024          57293
M017          49946
M010          47601
M021          46509
M003          40682
M005          35563
M008          35513
M022          31029
M012          30370
M016          29635
M006          27373
T005          27136
T003          26418
T002          26224
M026          25457
T004          20193
M004          20055
T001          16601
M027          14817
M023          12551
M001          12177
M002           9553
M030           8511
M028           7817
M029           7782
D004           5904
M025           4959
M011           4051
M031           2851
D001            519
D002            413
LEAVEHOME         4
ENTERHOME         1
Name: count, dtype: int64

In [18]:
activities = df[df["value"].str.contains(
    "begin|end",
    case=False,
    na=False
)]

activities.head(20)

,date,time,sensor,value,timestamp
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589
48,2010-11-04,05:40:43.642664,M003,OFF Sleeping end,2010-11-04 05:40:43.642664
52,2010-11-04,05:40:51.303739,M004,ON Bed_to_Toilet begin,2010-11-04 05:40:51.303739
63,2010-11-04,05:43:30.279021,M004,OFF Bed_to_Toilet end,2010-11-04 05:43:30.279021
68,2010-11-04,05:43:45.7324,M003,ON Sleeping begin,2010-11-04 05:43:45.732400
172,2010-11-04,08:01:12.28297,M003,OFF Sleeping end,2010-11-04 08:01:12.282970
266,2010-11-04,08:11:09.966157,M018,ON Meal_Preparation begin,2010-11-04 08:11:09.966157
520,2010-11-04,08:27:02.801314,M018,OFF Meal_Preparation end,2010-11-04 08:27:02.801314
659,2010-11-04,08:33:52.929406,M018,ON Meal_Preparation begin,2010-11-04 08:33:52.929406
707,2010-11-04,08:35:45.822482,M018,OFF Meal_Preparation end,2010-11-04 08:35:45.822482
934,2010-11-04,09:29:23.223133,M009,ON Relax begin,2010-11-04 09:29:23.223133
953,2010-11-04,09:34:05.78057,M009,OFF Relax end,2010-11-04 09:34:05.780570
962,2010-11-04,09:34:16.851472,M031,ON Housekeeping begin,2010-11-04 09:34:16.851472
1047,2010-11-04,09:44:40.315639,M031,OFF Housekeeping end,2010-11-04 09:44:40.315639
1129,2010-11-04,09:48:52.342223,M018,ON Meal_Preparation begin,2010-11-04 09:48:52.342223
1228,2010-11-04,09:53:02.954445,M018,OFF Meal_Preparation end,2010-11-04 09:53:02.954445
1261,2010-11-04,09:54:58.753743,M018,ON Meal_Preparation begin,2010-11-04 09:54:58.753743
1307,2010-11-04,09:56:27.334395,M018,OFF Meal_Preparation end,2010-11-04 09:56:27.334395
1318,2010-11-04,09:56:41.831135,M014,ON Eating begin,2010-11-04 09:56:41.831135
1339,2010-11-04,09:59:04.438334,M014,OFF Eating end,2010-11-04 09:59:04.438334

In [19]:
print("Number of activity annotations:", len(activities))

Number of activity annotations: 12954

In [20]:
activities["value"].unique()

array(['ON Sleeping begin', 'OFF Sleeping end', 'ON Bed_to_Toilet begin',
       'OFF Bed_to_Toilet end', 'ON Meal_Preparation begin',
       'OFF Meal_Preparation end', 'ON Relax begin', 'OFF Relax end',
       'ON Housekeeping begin', 'OFF Housekeeping end', 'ON Eating begin',
       'OFF Eating end', 'ON Wash_Dishes begin', 'OFF Wash_Dishes end',
       'OPEN Leave_Home begin', 'CLOSE Leave_Home end',
       'OPEN Enter_Home begin', 'CLOSE Enter_Home end', 'ON Work begin',
       'OFF Work end', 'ON Meal_Preparation end', 'OFF Sleeping begin',
       'ON Sleeping end', 'ON Eating end', 'ON Relax end', 'ON Work end',
       'ON Respirate begin', 'OFF Respirate end',
       'OFF Bed_to_Toilet begin', 'ON Bed_to_Toilet end',
       'OFF Relax begin', 'ON Leave_Home end', 'ON Enter_Home begin',
       'OFF Meal_Preparation begin', 'OFF Leave_Home end',
       'CLOSE Enter_Home begin', 'OFF Enter_Home end',
       'OFF Leave_Home begin', 'O Relax begin', 'OF Meal_Preparation end',
       'CLOSE Leave_Home begin', 'ON Leave_Home begin',
       'OFF Eating begin', '25 Sleeping end'], dtype=object)

In [22]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\nFirst date:")
print(df["timestamp"].min())

print("\nLast date:")
print(df["timestamp"].max())

Number of rows: 1719558
Number of columns: 5

First date:
2010-11-04 00:03:50.209589

Last date:
2011-06-11 23:58:10.004834

In [36]:
df["sensor_type"] = df["sensor"].str[0]

df[["sensor", "sensor_type"]].drop_duplicates().head(30)

    sensor sensor_type
0     M003           M
2     T002           T
3     T003           T
4     T004           T
5     T005           T
8     T001           T
28    M002           M
42    M007           M
50    M005           M
52    M004           M
193   M006           M
194   M008           M
196   M020           M
209   M010           M
213   M011           M
221   M012           M
222   M013           M
228   M014           M
234   M009           M
266   M018           M
267   M019           M
268   M015           M
344   M016           M
513   M017           M
526   M021           M
528   M022           M
532   M023           M
639   M001           M
762   M024           M
900   D002           D

In [37]:
df["sensor_type"].value_counts()

sensor_type
M    1596145
T     116572
D       6836
L          4
E          1
Name: count, dtype: int64

In [38]:
activities = df[
    df["value"].str.contains(
        "begin|end",
        case=False,
        na=False
    )
]

print("Number of activity annotations:", len(activities))

Number of activity annotations: 12954

In [42]:
activities["value"].unique()

array(['ON Sleeping begin', 'OFF Sleeping end', 'ON Bed_to_Toilet begin',
       'OFF Bed_to_Toilet end', 'ON Meal_Preparation begin',
       'OFF Meal_Preparation end', 'ON Relax begin', 'OFF Relax end',
       'ON Housekeeping begin', 'OFF Housekeeping end', 'ON Eating begin',
       'OFF Eating end', 'ON Wash_Dishes begin', 'OFF Wash_Dishes end',
       'OPEN Leave_Home begin', 'CLOSE Leave_Home end',
       'OPEN Enter_Home begin', 'CLOSE Enter_Home end', 'ON Work begin',
       'OFF Work end', 'ON Meal_Preparation end', 'OFF Sleeping begin',
       'ON Sleeping end', 'ON Eating end', 'ON Relax end', 'ON Work end',
       'ON Respirate begin', 'OFF Respirate end',
       'OFF Bed_to_Toilet begin', 'ON Bed_to_Toilet end',
       'OFF Relax begin', 'ON Leave_Home end', 'ON Enter_Home begin',
       'OFF Meal_Preparation begin', 'OFF Leave_Home end',
       'CLOSE Enter_Home begin', 'OFF Enter_Home end',
       'OFF Leave_Home begin', 'O Relax begin', 'OF Meal_Preparation end',
       'CLOSE Leave_Home begin', 'ON Leave_Home begin',
       'OFF Eating begin', '25 Sleeping end'], dtype=object)

In [43]:
activities["value"].value_counts()

value
ON Relax begin                2915
OFF Relax end                 2905
ON Meal_Preparation begin     1604
OFF Meal_Preparation end      1598
CLOSE Enter_Home end           430
OPEN Leave_Home begin          427
CLOSE Leave_Home end           425
OPEN Enter_Home begin          425
ON Sleeping begin              398
OFF Sleeping end               396
ON Eating begin                256
OFF Eating end                 254
ON Work begin                  171
OFF Work end                   168
ON Bed_to_Toilet begin         156
OFF Bed_to_Toilet end          154
ON Wash_Dishes begin            65
OFF Wash_Dishes end             65
ON Housekeeping begin           33
OFF Housekeeping end            33
ON Relax end                    14
ON Meal_Preparation end          7
ON Respirate begin               6
OFF Respirate end                6
ON Enter_Home begin              5
OFF Leave_Home end               5
ON Sleeping end                  4
OFF Sleeping begin               3
ON Work end                      3
ON Eating end                    3
ON Bed_to_Toilet end             3
OFF Relax begin                  3
OFF Meal_Preparation begin       2
ON Leave_Home begin              2
ON Leave_Home end                1
OFF Bed_to_Toilet begin          1
CLOSE Enter_Home begin           1
OFF Enter_Home end               1
O Relax begin                    1
OFF Leave_Home begin             1
OF Meal_Preparation end          1
CLOSE Leave_Home begin           1
OFF Eating begin                 1
25 Sleeping end                  1
Name: count, dtype: int64

In [44]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print(df["timestamp"].min())
print(df["timestamp"].max())

Number of rows: 1719558
Number of columns: 6
2010-11-04 00:03:50.209589
2011-06-11 23:58:10.004834

In [45]:
print(df["sensor"].unique())
print("Number of sensors:", df["sensor"].nunique())

['M003' 'T002' 'T003' 'T004' 'T005' 'T001' 'M002' 'M007' 'M005' 'M004'
 'M006' 'M008' 'M020' 'M010' 'M011' 'M012' 'M013' 'M014' 'M009' 'M018'
 'M019' 'M015' 'M016' 'M017' 'M021' 'M022' 'M023' 'M001' 'M024' 'D002'
 'M031' 'D004' 'M030' 'M029' 'M028' 'D001' 'M026' 'M027' 'M025'
 'LEAVEHOME' 'ENTERHOME']
Number of sensors: 41

In [46]:
df["sensor_type"] = df["sensor"].str[0]
print(df["sensor_type"].value_counts())

sensor_type
M    1596145
T     116572
D       6836
L          4
E          1
Name: count, dtype: int64

In [47]:
activities = df[
    df["value"].str.contains(
        "begin|end",
        case=False,
        na=False
    )
]

print("Number of activity annotations:", len(activities))
print(activities["value"].unique())

Number of activity annotations: 12954
['ON Sleeping begin' 'OFF Sleeping end' 'ON Bed_to_Toilet begin'
 'OFF Bed_to_Toilet end' 'ON Meal_Preparation begin'
 'OFF Meal_Preparation end' 'ON Relax begin' 'OFF Relax end'
 'ON Housekeeping begin' 'OFF Housekeeping end' 'ON Eating begin'
 'OFF Eating end' 'ON Wash_Dishes begin' 'OFF Wash_Dishes end'
 'OPEN Leave_Home begin' 'CLOSE Leave_Home end' 'OPEN Enter_Home begin'
 'CLOSE Enter_Home end' 'ON Work begin' 'OFF Work end'
 'ON Meal_Preparation end' 'OFF Sleeping begin' 'ON Sleeping end'
 'ON Eating end' 'ON Relax end' 'ON Work end' 'ON Respirate begin'
 'OFF Respirate end' 'OFF Bed_to_Toilet begin' 'ON Bed_to_Toilet end'
 'OFF Relax begin' 'ON Leave_Home end' 'ON Enter_Home begin'
 'OFF Meal_Preparation begin' 'OFF Leave_Home end'
 'CLOSE Enter_Home begin' 'OFF Enter_Home end' 'OFF Leave_Home begin'
 'O Relax begin' 'OF Meal_Preparation end' 'CLOSE Leave_Home begin'
 'ON Leave_Home begin' 'OFF Eating begin' '25 Sleeping end']

In [48]:
activities["value"].value_counts()

value
ON Relax begin                2915
OFF Relax end                 2905
ON Meal_Preparation begin     1604
OFF Meal_Preparation end      1598
CLOSE Enter_Home end           430
OPEN Leave_Home begin          427
CLOSE Leave_Home end           425
OPEN Enter_Home begin          425
ON Sleeping begin              398
OFF Sleeping end               396
ON Eating begin                256
OFF Eating end                 254
ON Work begin                  171
OFF Work end                   168
ON Bed_to_Toilet begin         156
OFF Bed_to_Toilet end          154
ON Wash_Dishes begin            65
OFF Wash_Dishes end             65
ON Housekeeping begin           33
OFF Housekeeping end            33
ON Relax end                    14
ON Meal_Preparation end          7
ON Respirate begin               6
OFF Respirate end                6
ON Enter_Home begin              5
OFF Leave_Home end               5
ON Sleeping end                  4
OFF Sleeping begin               3
ON Work end                      3
ON Eating end                    3
ON Bed_to_Toilet end             3
OFF Relax begin                  3
OFF Meal_Preparation begin       2
ON Leave_Home begin              2
ON Leave_Home end                1
OFF Bed_to_Toilet begin          1
CLOSE Enter_Home begin           1
OFF Enter_Home end               1
O Relax begin                    1
OFF Leave_Home begin             1
OF Meal_Preparation end          1
CLOSE Leave_Home begin           1
OFF Eating begin                 1
25 Sleeping end                  1
Name: count, dtype: int64

In [ ]:

motion_sensors = df[df["sensor_type"] == "M"]["sensor"].value_counts()

print(motion_sensors)

sensor
M009    263489
M020    162204
M019    157833
M015     98320
M007     94099
M014     89186
M013     86663
M018     82256
M024     57293
M017     49946
M010     47601
M021     46509
M003     40682
M005     35563
M008     35513
M022     31029
M012     30370
M016     29635
M006     27373
M026     25457
M004     20055
M027     14817
M023     12551
M001     12177
M002      9553
M030      8511
M028      7817
M029      7782
M025      4959
M011      4051
M031      2851
Name: count, dtype: int64

In [50]:
door_sensors = df[df["sensor_type"] == "D"]["sensor"].value_counts()

print(door_sensors)

sensor
D004    5904
D001     519
D002     413
Name: count, dtype: int64

In [ ]:

print(df["value"].value_counts().head(30))

value
OFF                          792410
ON                           792335
23.5                           9110
23                             8912
22.5                           8414
24                             8120
22                             7862
21.5                           7603
24.5                           7030
21                             6534
20.5                           5312
25                             5293
20                             4556
19.5                           4260
25.5                           4198
19                             3844
18.5                           3814
26                             3197
ON Relax begin                 2915
OFF Relax end                  2905
18                             2871
26.5                           2568
OPEN                           2563
CLOSE                          2562
27                             1904
27.5                           1673
ON Meal_Preparation begin      1604
OFF Meal_Preparation end       1598
28                             1340
28.5                           1264
Name: count, dtype: int64

In [52]:
print(df[df["sensor_type"] == "M"][["sensor", "value"]].head(30))

   sensor                   value
0    M003       ON Sleeping begin
1    M003                     OFF
15   M003                      ON
16   M003                     OFF
20   M003                      ON
22   M003                     OFF
23   M003                      ON
24   M003                     OFF
27   M003                      ON
28   M002                      ON
29   M002                     OFF
30   M003                     OFF
32   M003                      ON
33   M002                      ON
34   M002                     OFF
35   M003                     OFF
40   M003                      ON
41   M002                      ON
42   M007                      ON
43   M002                     OFF
44   M007                     OFF
45   M003                     OFF
46   M003                      ON
47   M007                      ON
48   M003        OFF Sleeping end
49   M003                      ON
50   M005                      ON
51   M003                     OFF
52   M004  ON Bed_to_Toilet begin
53   M005                     OFF

In [53]:
print(df[df["sensor_type"] == "D"][["sensor", "value"]].head(30))

     sensor                  value
900    D002                   OPEN
910    D002                  CLOSE
1050   D004                   OPEN
1056   D004                  CLOSE
2330   D001                   OPEN
2332   D001                  CLOSE
2346   D004  OPEN Leave_Home begin
2348   D004   CLOSE Leave_Home end
2351   D004  OPEN Enter_Home begin
2354   D004   CLOSE Enter_Home end
2365   D004  OPEN Leave_Home begin
2367   D004   CLOSE Leave_Home end
2370   D004  OPEN Enter_Home begin
2373   D004   CLOSE Enter_Home end
2380   D004                   OPEN
2384   D004                  CLOSE
2414   D004                   OPEN
2419   D004                  CLOSE
2455   D002                   OPEN
2458   D002                  CLOSE
2791   D001                   OPEN
2795   D001                  CLOSE
3501   D004                   OPEN
3508   D004                  CLOSE
3711   D002                   OPEN
3720   D002                  CLOSE
4090   D004                   OPEN
4097   D004                  CLOSE
7235   D004                   OPEN
7238   D004                  CLOSE