In [64]:
import pandas as pd

In [65]:
file_path = "../aruba.txt"

data = []

with open(file_path, "r") as file:
    for line in file:
        parts = line.strip().split()

        date = parts[0]
        time = parts[1]
        sensor = parts[2]
        value = " ".join(parts[3:])

        data.append([date, time, sensor, value])

df = pd.DataFrame(
    data,
    columns=["date", "time", "sensor", "value"]
)

df.head(20)

          date             time sensor              value
0   2010-11-04  00:03:50.209589   M003  ON Sleeping begin
1   2010-11-04  00:03:57.399391   M003                OFF
2   2010-11-04  00:15:08.984841   T002               21.5
3   2010-11-04  00:30:19.185547   T003                 21
4   2010-11-04  00:30:19.385336   T004                 21
5   2010-11-04   00:35:22.24587   T005               20.5
6   2010-11-04  00:40:25.428962   T005                 21
7   2010-11-04  00:45:28.658171   T005               20.5
8   2010-11-04  01:05:42.269469   T001                 20
9   2010-11-04  01:15:48.936777   T002                 21
10  2010-11-04  01:30:59.100184   T003               20.5
11  2010-11-04  01:46:09.301846   T005                 20
12  2010-11-04  01:56:16.059687   T004               20.5
13  2010-11-04  02:21:32.138203   T001               19.5
14  2010-11-04  02:21:32.228625   T002               20.5
15  2010-11-04  02:32:33.351906   M003                 ON
16  2010-11-04  02:32:38.895958   M003                OFF
17  2010-11-04  02:41:45.231875   T003                 20
18  2010-11-04  02:56:55.529628   T005               19.5
19  2010-11-04  03:22:11.942589   T004                 20

In [66]:
df.shape[0]

1719558

In [67]:
df.isnull().sum()

date      0
time      0
sensor    0
value     0
dtype: int64

In [68]:
df.head(20)

          date             time sensor              value
0   2010-11-04  00:03:50.209589   M003  ON Sleeping begin
1   2010-11-04  00:03:57.399391   M003                OFF
2   2010-11-04  00:15:08.984841   T002               21.5
3   2010-11-04  00:30:19.185547   T003                 21
4   2010-11-04  00:30:19.385336   T004                 21
5   2010-11-04   00:35:22.24587   T005               20.5
6   2010-11-04  00:40:25.428962   T005                 21
7   2010-11-04  00:45:28.658171   T005               20.5
8   2010-11-04  01:05:42.269469   T001                 20
9   2010-11-04  01:15:48.936777   T002                 21
10  2010-11-04  01:30:59.100184   T003               20.5
11  2010-11-04  01:46:09.301846   T005                 20
12  2010-11-04  01:56:16.059687   T004               20.5
13  2010-11-04  02:21:32.138203   T001               19.5
14  2010-11-04  02:21:32.228625   T002               20.5
15  2010-11-04  02:32:33.351906   M003                 ON
16  2010-11-04  02:32:38.895958   M003                OFF
17  2010-11-04  02:41:45.231875   T003                 20
18  2010-11-04  02:56:55.529628   T005               19.5
19  2010-11-04  03:22:11.942589   T004                 20

In [69]:
df["timestamp"] = pd.to_datetime(
    df["date"] + " " + df["time"],
    format="mixed"
)

df.head()

,date,time,sensor,value,timestamp
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391
2,2010-11-04,00:15:08.984841,T002,21.5,2010-11-04 00:15:08.984841
3,2010-11-04,00:30:19.185547,T003,21,2010-11-04 00:30:19.185547
4,2010-11-04,00:30:19.385336,T004,21,2010-11-04 00:30:19.385336

In [70]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

Number of rows: 1719558
Number of columns: 5

In [71]:
print(df["sensor"].unique())
print(df["sensor"].nunique())

['M003' 'T002' 'T003' 'T004' 'T005' 'T001' 'M002' 'M007' 'M005' 'M004'
 'M006' 'M008' 'M020' 'M010' 'M011' 'M012' 'M013' 'M014' 'M009' 'M018'
 'M019' 'M015' 'M016' 'M017' 'M021' 'M022' 'M023' 'M001' 'M024' 'D002'
 'M031' 'D004' 'M030' 'M029' 'M028' 'D001' 'M026' 'M027' 'M025'
 'LEAVEHOME' 'ENTERHOME']
41

In [72]:
df["sensor"].value_counts()

sensor
M009         263489
M020         162204
M019         157833
M015          98320
M007          94099
M014          89186
M013          86663
M018          82256
M024          57293
M017          49946
M010          47601
M021          46509
M003          40682
M005          35563
M008          35513
M022          31029
M012          30370
M016          29635
M006          27373
T005          27136
T003          26418
T002          26224
M026          25457
T004          20193
M004          20055
T001          16601
M027          14817
M023          12551
M001          12177
M002           9553
M030           8511
M028           7817
M029           7782
D004           5904
M025           4959
M011           4051
M031           2851
D001            519
D002            413
LEAVEHOME         4
ENTERHOME         1
Name: count, dtype: int64

In [73]:
activities = df[df["value"].str.contains(
    "begin|end",
    case=False,
    na=False
)]

activities.head(20)

,date,time,sensor,value,timestamp
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589
48,2010-11-04,05:40:43.642664,M003,OFF Sleeping end,2010-11-04 05:40:43.642664
52,2010-11-04,05:40:51.303739,M004,ON Bed_to_Toilet begin,2010-11-04 05:40:51.303739
63,2010-11-04,05:43:30.279021,M004,OFF Bed_to_Toilet end,2010-11-04 05:43:30.279021
68,2010-11-04,05:43:45.7324,M003,ON Sleeping begin,2010-11-04 05:43:45.732400
172,2010-11-04,08:01:12.28297,M003,OFF Sleeping end,2010-11-04 08:01:12.282970
266,2010-11-04,08:11:09.966157,M018,ON Meal_Preparation begin,2010-11-04 08:11:09.966157
520,2010-11-04,08:27:02.801314,M018,OFF Meal_Preparation end,2010-11-04 08:27:02.801314
659,2010-11-04,08:33:52.929406,M018,ON Meal_Preparation begin,2010-11-04 08:33:52.929406
707,2010-11-04,08:35:45.822482,M018,OFF Meal_Preparation end,2010-11-04 08:35:45.822482
934,2010-11-04,09:29:23.223133,M009,ON Relax begin,2010-11-04 09:29:23.223133
953,2010-11-04,09:34:05.78057,M009,OFF Relax end,2010-11-04 09:34:05.780570
962,2010-11-04,09:34:16.851472,M031,ON Housekeeping begin,2010-11-04 09:34:16.851472
1047,2010-11-04,09:44:40.315639,M031,OFF Housekeeping end,2010-11-04 09:44:40.315639
1129,2010-11-04,09:48:52.342223,M018,ON Meal_Preparation begin,2010-11-04 09:48:52.342223
1228,2010-11-04,09:53:02.954445,M018,OFF Meal_Preparation end,2010-11-04 09:53:02.954445
1261,2010-11-04,09:54:58.753743,M018,ON Meal_Preparation begin,2010-11-04 09:54:58.753743
1307,2010-11-04,09:56:27.334395,M018,OFF Meal_Preparation end,2010-11-04 09:56:27.334395
1318,2010-11-04,09:56:41.831135,M014,ON Eating begin,2010-11-04 09:56:41.831135
1339,2010-11-04,09:59:04.438334,M014,OFF Eating end,2010-11-04 09:59:04.438334

In [74]:
print("Number of activity annotations:", len(activities))

Number of activity annotations: 12954

In [75]:
activities["value"].unique()

array(['ON Sleeping begin', 'OFF Sleeping end', 'ON Bed_to_Toilet begin',
       'OFF Bed_to_Toilet end', 'ON Meal_Preparation begin',
       'OFF Meal_Preparation end', 'ON Relax begin', 'OFF Relax end',
       'ON Housekeeping begin', 'OFF Housekeeping end', 'ON Eating begin',
       'OFF Eating end', 'ON Wash_Dishes begin', 'OFF Wash_Dishes end',
       'OPEN Leave_Home begin', 'CLOSE Leave_Home end',
       'OPEN Enter_Home begin', 'CLOSE Enter_Home end', 'ON Work begin',
       'OFF Work end', 'ON Meal_Preparation end', 'OFF Sleeping begin',
       'ON Sleeping end', 'ON Eating end', 'ON Relax end', 'ON Work end',
       'ON Respirate begin', 'OFF Respirate end',
       'OFF Bed_to_Toilet begin', 'ON Bed_to_Toilet end',
       'OFF Relax begin', 'ON Leave_Home end', 'ON Enter_Home begin',
       'OFF Meal_Preparation begin', 'OFF Leave_Home end',
       'CLOSE Enter_Home begin', 'OFF Enter_Home end',
       'OFF Leave_Home begin', 'O Relax begin', 'OF Meal_Preparation end',
       'CLOSE Leave_Home begin', 'ON Leave_Home begin',
       'OFF Eating begin', '25 Sleeping end'], dtype=object)

In [76]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\nFirst date:")
print(df["timestamp"].min())

print("\nLast date:")
print(df["timestamp"].max())

Number of rows: 1719558
Number of columns: 5

First date:
2010-11-04 00:03:50.209589

Last date:
2011-06-11 23:58:10.004834

In [77]:
df["sensor_type"] = df["sensor"].str[0]

df[["sensor", "sensor_type"]].drop_duplicates().head(30)

    sensor sensor_type
0     M003           M
2     T002           T
3     T003           T
4     T004           T
5     T005           T
8     T001           T
28    M002           M
42    M007           M
50    M005           M
52    M004           M
193   M006           M
194   M008           M
196   M020           M
209   M010           M
213   M011           M
221   M012           M
222   M013           M
228   M014           M
234   M009           M
266   M018           M
267   M019           M
268   M015           M
344   M016           M
513   M017           M
526   M021           M
528   M022           M
532   M023           M
639   M001           M
762   M024           M
900   D002           D

In [78]:
df["sensor_type"].value_counts()

sensor_type
M    1596145
T     116572
D       6836
L          4
E          1
Name: count, dtype: int64

In [79]:
activities = df[
    df["value"].str.contains(
        "begin|end",
        case=False,
        na=False
    )
]

print("Number of activity annotations:", len(activities))

Number of activity annotations: 12954

In [80]:
activities["value"].unique()

array(['ON Sleeping begin', 'OFF Sleeping end', 'ON Bed_to_Toilet begin',
       'OFF Bed_to_Toilet end', 'ON Meal_Preparation begin',
       'OFF Meal_Preparation end', 'ON Relax begin', 'OFF Relax end',
       'ON Housekeeping begin', 'OFF Housekeeping end', 'ON Eating begin',
       'OFF Eating end', 'ON Wash_Dishes begin', 'OFF Wash_Dishes end',
       'OPEN Leave_Home begin', 'CLOSE Leave_Home end',
       'OPEN Enter_Home begin', 'CLOSE Enter_Home end', 'ON Work begin',
       'OFF Work end', 'ON Meal_Preparation end', 'OFF Sleeping begin',
       'ON Sleeping end', 'ON Eating end', 'ON Relax end', 'ON Work end',
       'ON Respirate begin', 'OFF Respirate end',
       'OFF Bed_to_Toilet begin', 'ON Bed_to_Toilet end',
       'OFF Relax begin', 'ON Leave_Home end', 'ON Enter_Home begin',
       'OFF Meal_Preparation begin', 'OFF Leave_Home end',
       'CLOSE Enter_Home begin', 'OFF Enter_Home end',
       'OFF Leave_Home begin', 'O Relax begin', 'OF Meal_Preparation end',
       'CLOSE Leave_Home begin', 'ON Leave_Home begin',
       'OFF Eating begin', '25 Sleeping end'], dtype=object)

In [81]:
activities["value"].value_counts()

value
ON Relax begin                2915
OFF Relax end                 2905
ON Meal_Preparation begin     1604
OFF Meal_Preparation end      1598
CLOSE Enter_Home end           430
OPEN Leave_Home begin          427
CLOSE Leave_Home end           425
OPEN Enter_Home begin          425
ON Sleeping begin              398
OFF Sleeping end               396
ON Eating begin                256
OFF Eating end                 254
ON Work begin                  171
OFF Work end                   168
ON Bed_to_Toilet begin         156
OFF Bed_to_Toilet end          154
ON Wash_Dishes begin            65
OFF Wash_Dishes end             65
ON Housekeeping begin           33
OFF Housekeeping end            33
ON Relax end                    14
ON Meal_Preparation end          7
ON Respirate begin               6
OFF Respirate end                6
ON Enter_Home begin              5
OFF Leave_Home end               5
ON Sleeping end                  4
OFF Sleeping begin               3
ON Work end                      3
ON Eating end                    3
ON Bed_to_Toilet end             3
OFF Relax begin                  3
OFF Meal_Preparation begin       2
ON Leave_Home begin              2
ON Leave_Home end                1
OFF Bed_to_Toilet begin          1
CLOSE Enter_Home begin           1
OFF Enter_Home end               1
O Relax begin                    1
OFF Leave_Home begin             1
OF Meal_Preparation end          1
CLOSE Leave_Home begin           1
OFF Eating begin                 1
25 Sleeping end                  1
Name: count, dtype: int64

In [82]:
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))
print(df["timestamp"].min())
print(df["timestamp"].max())

Number of rows: 1719558
Number of columns: 6
2010-11-04 00:03:50.209589
2011-06-11 23:58:10.004834

In [83]:
print(df["sensor"].unique())
print("Number of sensors:", df["sensor"].nunique())

['M003' 'T002' 'T003' 'T004' 'T005' 'T001' 'M002' 'M007' 'M005' 'M004'
 'M006' 'M008' 'M020' 'M010' 'M011' 'M012' 'M013' 'M014' 'M009' 'M018'
 'M019' 'M015' 'M016' 'M017' 'M021' 'M022' 'M023' 'M001' 'M024' 'D002'
 'M031' 'D004' 'M030' 'M029' 'M028' 'D001' 'M026' 'M027' 'M025'
 'LEAVEHOME' 'ENTERHOME']
Number of sensors: 41

In [84]:
df["sensor_type"] = df["sensor"].str[0]
print(df["sensor_type"].value_counts())

sensor_type
M    1596145
T     116572
D       6836
L          4
E          1
Name: count, dtype: int64

In [85]:
activities = df[
    df["value"].str.contains(
        "begin|end",
        case=False,
        na=False
    )
]

print("Number of activity annotations:", len(activities))
print(activities["value"].unique())

Number of activity annotations: 12954
['ON Sleeping begin' 'OFF Sleeping end' 'ON Bed_to_Toilet begin'
 'OFF Bed_to_Toilet end' 'ON Meal_Preparation begin'
 'OFF Meal_Preparation end' 'ON Relax begin' 'OFF Relax end'
 'ON Housekeeping begin' 'OFF Housekeeping end' 'ON Eating begin'
 'OFF Eating end' 'ON Wash_Dishes begin' 'OFF Wash_Dishes end'
 'OPEN Leave_Home begin' 'CLOSE Leave_Home end' 'OPEN Enter_Home begin'
 'CLOSE Enter_Home end' 'ON Work begin' 'OFF Work end'
 'ON Meal_Preparation end' 'OFF Sleeping begin' 'ON Sleeping end'
 'ON Eating end' 'ON Relax end' 'ON Work end' 'ON Respirate begin'
 'OFF Respirate end' 'OFF Bed_to_Toilet begin' 'ON Bed_to_Toilet end'
 'OFF Relax begin' 'ON Leave_Home end' 'ON Enter_Home begin'
 'OFF Meal_Preparation begin' 'OFF Leave_Home end'
 'CLOSE Enter_Home begin' 'OFF Enter_Home end' 'OFF Leave_Home begin'
 'O Relax begin' 'OF Meal_Preparation end' 'CLOSE Leave_Home begin'
 'ON Leave_Home begin' 'OFF Eating begin' '25 Sleeping end']

In [86]:
activities["value"].value_counts()

value
ON Relax begin                2915
OFF Relax end                 2905
ON Meal_Preparation begin     1604
OFF Meal_Preparation end      1598
CLOSE Enter_Home end           430
OPEN Leave_Home begin          427
CLOSE Leave_Home end           425
OPEN Enter_Home begin          425
ON Sleeping begin              398
OFF Sleeping end               396
ON Eating begin                256
OFF Eating end                 254
ON Work begin                  171
OFF Work end                   168
ON Bed_to_Toilet begin         156
OFF Bed_to_Toilet end          154
ON Wash_Dishes begin            65
OFF Wash_Dishes end             65
ON Housekeeping begin           33
OFF Housekeeping end            33
ON Relax end                    14
ON Meal_Preparation end          7
ON Respirate begin               6
OFF Respirate end                6
ON Enter_Home begin              5
OFF Leave_Home end               5
ON Sleeping end                  4
OFF Sleeping begin               3
ON Work end                      3
ON Eating end                    3
ON Bed_to_Toilet end             3
OFF Relax begin                  3
OFF Meal_Preparation begin       2
ON Leave_Home begin              2
ON Leave_Home end                1
OFF Bed_to_Toilet begin          1
CLOSE Enter_Home begin           1
OFF Enter_Home end               1
O Relax begin                    1
OFF Leave_Home begin             1
OF Meal_Preparation end          1
CLOSE Leave_Home begin           1
OFF Eating begin                 1
25 Sleeping end                  1
Name: count, dtype: int64

In [87]:

motion_sensors = df[df["sensor_type"] == "M"]["sensor"].value_counts()

print(motion_sensors)

sensor
M009    263489
M020    162204
M019    157833
M015     98320
M007     94099
M014     89186
M013     86663
M018     82256
M024     57293
M017     49946
M010     47601
M021     46509
M003     40682
M005     35563
M008     35513
M022     31029
M012     30370
M016     29635
M006     27373
M026     25457
M004     20055
M027     14817
M023     12551
M001     12177
M002      9553
M030      8511
M028      7817
M029      7782
M025      4959
M011      4051
M031      2851
Name: count, dtype: int64

In [88]:
door_sensors = df[df["sensor_type"] == "D"]["sensor"].value_counts()

print(door_sensors)

sensor
D004    5904
D001     519
D002     413
Name: count, dtype: int64

In [89]:

print(df["value"].value_counts().head(30))

value
OFF                          792410
ON                           792335
23.5                           9110
23                             8912
22.5                           8414
24                             8120
22                             7862
21.5                           7603
24.5                           7030
21                             6534
20.5                           5312
25                             5293
20                             4556
19.5                           4260
25.5                           4198
19                             3844
18.5                           3814
26                             3197
ON Relax begin                 2915
OFF Relax end                  2905
18                             2871
26.5                           2568
OPEN                           2563
CLOSE                          2562
27                             1904
27.5                           1673
ON Meal_Preparation begin      1604
OFF Meal_Preparation end       1598
28                             1340
28.5                           1264
Name: count, dtype: int64

In [90]:
print(df[df["sensor_type"] == "M"][["sensor", "value"]].head(30))

   sensor                   value
0    M003       ON Sleeping begin
1    M003                     OFF
15   M003                      ON
16   M003                     OFF
20   M003                      ON
22   M003                     OFF
23   M003                      ON
24   M003                     OFF
27   M003                      ON
28   M002                      ON
29   M002                     OFF
30   M003                     OFF
32   M003                      ON
33   M002                      ON
34   M002                     OFF
35   M003                     OFF
40   M003                      ON
41   M002                      ON
42   M007                      ON
43   M002                     OFF
44   M007                     OFF
45   M003                     OFF
46   M003                      ON
47   M007                      ON
48   M003        OFF Sleeping end
49   M003                      ON
50   M005                      ON
51   M003                     OFF
52   M004  ON Bed_to_Toilet begin
53   M005                     OFF

In [91]:
print(df[df["sensor_type"] == "D"][["sensor", "value"]].head(30))

     sensor                  value
900    D002                   OPEN
910    D002                  CLOSE
1050   D004                   OPEN
1056   D004                  CLOSE
2330   D001                   OPEN
2332   D001                  CLOSE
2346   D004  OPEN Leave_Home begin
2348   D004   CLOSE Leave_Home end
2351   D004  OPEN Enter_Home begin
2354   D004   CLOSE Enter_Home end
2365   D004  OPEN Leave_Home begin
2367   D004   CLOSE Leave_Home end
2370   D004  OPEN Enter_Home begin
2373   D004   CLOSE Enter_Home end
2380   D004                   OPEN
2384   D004                  CLOSE
2414   D004                   OPEN
2419   D004                  CLOSE
2455   D002                   OPEN
2458   D002                  CLOSE
2791   D001                   OPEN
2795   D001                  CLOSE
3501   D004                   OPEN
3508   D004                  CLOSE
3711   D002                   OPEN
3720   D002                  CLOSE
4090   D004                   OPEN
4097   D004                  CLOSE
7235   D004                   OPEN
7238   D004                  CLOSE

In [92]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

df["hour"] = df["timestamp"].dt.hour

def get_period(hour):
    if 5 <= hour < 12:
        return "morning"
    elif 12 <= hour < 17:
        return "afternoon"
    elif 17 <= hour < 21:
        return "evening"
    else:
        return "night"

df["time_period"] = df["hour"].apply(get_period)

In [93]:
df.head(30)

,date,time,sensor,value,timestamp,sensor_type,hour,time_period
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M,0,night
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M,0,night
2,2010-11-04,00:15:08.984841,T002,21.5,2010-11-04 00:15:08.984841,T,0,night
3,2010-11-04,00:30:19.185547,T003,21,2010-11-04 00:30:19.185547,T,0,night
4,2010-11-04,00:30:19.385336,T004,21,2010-11-04 00:30:19.385336,T,0,night
5,2010-11-04,00:35:22.24587,T005,20.5,2010-11-04 00:35:22.245870,T,0,night
6,2010-11-04,00:40:25.428962,T005,21,2010-11-04 00:40:25.428962,T,0,night
7,2010-11-04,00:45:28.658171,T005,20.5,2010-11-04 00:45:28.658171,T,0,night
8,2010-11-04,01:05:42.269469,T001,20,2010-11-04 01:05:42.269469,T,1,night
9,2010-11-04,01:15:48.936777,T002,21,2010-11-04 01:15:48.936777,T,1,night
10,2010-11-04,01:30:59.100184,T003,20.5,2010-11-04 01:30:59.100184,T,1,night
11,2010-11-04,01:46:09.301846,T005,20,2010-11-04 01:46:09.301846,T,1,night
12,2010-11-04,01:56:16.059687,T004,20.5,2010-11-04 01:56:16.059687,T,1,night
13,2010-11-04,02:21:32.138203,T001,19.5,2010-11-04 02:21:32.138203,T,2,night
14,2010-11-04,02:21:32.228625,T002,20.5,2010-11-04 02:21:32.228625,T,2,night
15,2010-11-04,02:32:33.351906,M003,ON,2010-11-04 02:32:33.351906,M,2,night
16,2010-11-04,02:32:38.895958,M003,OFF,2010-11-04 02:32:38.895958,M,2,night
17,2010-11-04,02:41:45.231875,T003,20,2010-11-04 02:41:45.231875,T,2,night
18,2010-11-04,02:56:55.529628,T005,19.5,2010-11-04 02:56:55.529628,T,2,night
19,2010-11-04,03:22:11.942589,T004,20,2010-11-04 03:22:11.942589,T,3,night
20,2010-11-04,03:42:21.82365,M003,ON,2010-11-04 03:42:21.823650,M,3,night
21,2010-11-04,03:42:25.128495,T002,20,2010-11-04 03:42:25.128495,T,3,night
22,2010-11-04,03:42:25.93973,M003,OFF,2010-11-04 03:42:25.939730,M,3,night
23,2010-11-04,03:49:52.412755,M003,ON,2010-11-04 03:49:52.412755,M,3,night
24,2010-11-04,03:49:57.473649,M003,OFF,2010-11-04 03:49:57.473649,M,3,night
25,2010-11-04,03:57:34.772738,T001,19,2010-11-04 03:57:34.772738,T,3,night
26,2010-11-04,03:57:34.856793,T003,19.5,2010-11-04 03:57:34.856793,T,3,night
27,2010-11-04,04:14:32.835757,M003,ON,2010-11-04 04:14:32.835757,M,4,night
28,2010-11-04,04:14:33.203704,M002,ON,2010-11-04 04:14:33.203704,M,4,night
29,2010-11-04,04:14:37.15509,M002,OFF,2010-11-04 04:14:37.155090,M,4,night

In [94]:
print(df.columns)

Index(['date', 'time', 'sensor', 'value', 'timestamp', 'sensor_type', 'hour',
       'time_period'],
      dtype='object')

In [95]:
print(df["sensor_type"].unique())

['M' 'T' 'D' 'L' 'E']

In [96]:
# Create activity_label
def get_activity(row):
    sensor = row["sensor_type"]
    value = row["value"]

    if sensor == "M":
        if value == 1:
            return "movement"
        else:
            return "no_movement"

    elif sensor == "D":
        if value == 1:
            return "door_open"
        else:
            return "door_closed"


    elif sensor == "T":
        return "temperature"


    else:
        return "unknown"


df["activity_label"] = df.apply(get_activity, axis=1)

In [97]:
print(df[["timestamp", "sensor_type", "value", "activity_label"]].head(20))

                    timestamp sensor_type              value activity_label
0  2010-11-04 00:03:50.209589           M  ON Sleeping begin    no_movement
1  2010-11-04 00:03:57.399391           M                OFF    no_movement
2  2010-11-04 00:15:08.984841           T               21.5    temperature
3  2010-11-04 00:30:19.185547           T                 21    temperature
4  2010-11-04 00:30:19.385336           T                 21    temperature
5  2010-11-04 00:35:22.245870           T               20.5    temperature
6  2010-11-04 00:40:25.428962           T                 21    temperature
7  2010-11-04 00:45:28.658171           T               20.5    temperature
8  2010-11-04 01:05:42.269469           T                 20    temperature
9  2010-11-04 01:15:48.936777           T                 21    temperature
10 2010-11-04 01:30:59.100184           T               20.5    temperature
11 2010-11-04 01:46:09.301846           T                 20    temperature
12 2010-11-04 01:56:16.059687           T               20.5    temperature
13 2010-11-04 02:21:32.138203           T               19.5    temperature
14 2010-11-04 02:21:32.228625           T               20.5    temperature
15 2010-11-04 02:32:33.351906           M                 ON    no_movement
16 2010-11-04 02:32:38.895958           M                OFF    no_movement
17 2010-11-04 02:41:45.231875           T                 20    temperature
18 2010-11-04 02:56:55.529628           T               19.5    temperature
19 2010-11-04 03:22:11.942589           T                 20    temperature

In [98]:
df.head(20)

,date,time,sensor,value,timestamp,sensor_type,hour,time_period,activity_label
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M,0,night,no_movement
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M,0,night,no_movement
2,2010-11-04,00:15:08.984841,T002,21.5,2010-11-04 00:15:08.984841,T,0,night,temperature
3,2010-11-04,00:30:19.185547,T003,21,2010-11-04 00:30:19.185547,T,0,night,temperature
4,2010-11-04,00:30:19.385336,T004,21,2010-11-04 00:30:19.385336,T,0,night,temperature
5,2010-11-04,00:35:22.24587,T005,20.5,2010-11-04 00:35:22.245870,T,0,night,temperature
6,2010-11-04,00:40:25.428962,T005,21,2010-11-04 00:40:25.428962,T,0,night,temperature
7,2010-11-04,00:45:28.658171,T005,20.5,2010-11-04 00:45:28.658171,T,0,night,temperature
8,2010-11-04,01:05:42.269469,T001,20,2010-11-04 01:05:42.269469,T,1,night,temperature
9,2010-11-04,01:15:48.936777,T002,21,2010-11-04 01:15:48.936777,T,1,night,temperature
10,2010-11-04,01:30:59.100184,T003,20.5,2010-11-04 01:30:59.100184,T,1,night,temperature
11,2010-11-04,01:46:09.301846,T005,20,2010-11-04 01:46:09.301846,T,1,night,temperature
12,2010-11-04,01:56:16.059687,T004,20.5,2010-11-04 01:56:16.059687,T,1,night,temperature
13,2010-11-04,02:21:32.138203,T001,19.5,2010-11-04 02:21:32.138203,T,2,night,temperature
14,2010-11-04,02:21:32.228625,T002,20.5,2010-11-04 02:21:32.228625,T,2,night,temperature
15,2010-11-04,02:32:33.351906,M003,ON,2010-11-04 02:32:33.351906,M,2,night,no_movement
16,2010-11-04,02:32:38.895958,M003,OFF,2010-11-04 02:32:38.895958,M,2,night,no_movement
17,2010-11-04,02:41:45.231875,T003,20,2010-11-04 02:41:45.231875,T,2,night,temperature
18,2010-11-04,02:56:55.529628,T005,19.5,2010-11-04 02:56:55.529628,T,2,night,temperature
19,2010-11-04,03:22:11.942589,T004,20,2010-11-04 03:22:11.942589,T,3,night,temperature

In [99]:
df = df[df["sensor_type"] != "T"].copy()

In [100]:
df.head(20)

,date,time,sensor,value,timestamp,sensor_type,hour,time_period,activity_label
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M,0,night,no_movement
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M,0,night,no_movement
15,2010-11-04,02:32:33.351906,M003,ON,2010-11-04 02:32:33.351906,M,2,night,no_movement
16,2010-11-04,02:32:38.895958,M003,OFF,2010-11-04 02:32:38.895958,M,2,night,no_movement
20,2010-11-04,03:42:21.82365,M003,ON,2010-11-04 03:42:21.823650,M,3,night,no_movement
22,2010-11-04,03:42:25.93973,M003,OFF,2010-11-04 03:42:25.939730,M,3,night,no_movement
23,2010-11-04,03:49:52.412755,M003,ON,2010-11-04 03:49:52.412755,M,3,night,no_movement
24,2010-11-04,03:49:57.473649,M003,OFF,2010-11-04 03:49:57.473649,M,3,night,no_movement
27,2010-11-04,04:14:32.835757,M003,ON,2010-11-04 04:14:32.835757,M,4,night,no_movement
28,2010-11-04,04:14:33.203704,M002,ON,2010-11-04 04:14:33.203704,M,4,night,no_movement
29,2010-11-04,04:14:37.15509,M002,OFF,2010-11-04 04:14:37.155090,M,4,night,no_movement
30,2010-11-04,04:14:39.470621,M003,OFF,2010-11-04 04:14:39.470621,M,4,night,no_movement
32,2010-11-04,04:34:17.62167,M003,ON,2010-11-04 04:34:17.621670,M,4,night,no_movement
33,2010-11-04,04:34:19.224926,M002,ON,2010-11-04 04:34:19.224926,M,4,night,no_movement
34,2010-11-04,04:34:20.849595,M002,OFF,2010-11-04 04:34:20.849595,M,4,night,no_movement
35,2010-11-04,04:34:21.407224,M003,OFF,2010-11-04 04:34:21.407224,M,4,night,no_movement
40,2010-11-04,05:40:27.708148,M003,ON,2010-11-04 05:40:27.708148,M,5,morning,no_movement
41,2010-11-04,05:40:29.816524,M002,ON,2010-11-04 05:40:29.816524,M,5,morning,no_movement
42,2010-11-04,05:40:32.342225,M007,ON,2010-11-04 05:40:32.342225,M,5,morning,no_movement
43,2010-11-04,05:40:33.109478,M002,OFF,2010-11-04 05:40:33.109478,M,5,morning,no_movement

In [101]:
print(df["sensor_type"].unique())

['M' 'D' 'L' 'E']

In [102]:
df["activity_label"].value_counts()

activity_label
no_movement    1596145
door_closed       6836
unknown              5
Name: count, dtype: int64

In [103]:
print(df[df["sensor_type"] == "M"]["value"].value_counts())

value
OFF                           792410
ON                            792335
ON Relax begin                  2915
OFF Relax end                   2905
ON Meal_Preparation begin       1604
OFF Meal_Preparation end        1598
ON Sleeping begin                398
OFF Sleeping end                 396
ON Eating begin                  256
OFF Eating end                   254
ON Work begin                    171
OFF Work end                     168
ON Bed_to_Toilet begin           156
OFF Bed_to_Toilet end            154
OFF Wash_Dishes end               65
ON Wash_Dishes begin              65
ONc                               44
OFFc                              39
ON Housekeeping begin             33
OFF Housekeeping end              33
ON5                               17
ON Relax end                      14
OFF5                              14
OFFcc                              8
ON Meal_Preparation end            7
ON Respirate begin                 6
OFF Respirate end                  6
OFF5c                              6
ON Enter_Home begin                5
ON5c                               5
OFF Leave_Home end                 5
ONcc                               5
ON Sleeping end                    4
OFF Sleeping begin                 3
ON Work end                        3
ON Eating end                      3
ON Bed_to_Toilet end               3
OFcF                               3
OFF Relax begin                    3
ONc5c                              2
OFF5cc                             2
OFF Meal_Preparation begin         2
ONc5                               2
ON Leave_Home begin                2
ONM026                             2
OFFc5                              2
ON55                               1
OFF Bed_to_Toilet begin            1
ON Leave_Home end                  1
OcFF                               1
OFF Enter_Home end                 1
OFFccc5                            1
O Relax begin                      1
OFF Leave_Home begin               1
OF Meal_Preparation end            1
OFF Eating begin                   1
ONM009                             1
ONM024                             1
Name: count, dtype: int64

In [104]:
print(df[df["sensor_type"] == "M"]["value"].value_counts())

value
OFF                           792410
ON                            792335
ON Relax begin                  2915
OFF Relax end                   2905
ON Meal_Preparation begin       1604
OFF Meal_Preparation end        1598
ON Sleeping begin                398
OFF Sleeping end                 396
ON Eating begin                  256
OFF Eating end                   254
ON Work begin                    171
OFF Work end                     168
ON Bed_to_Toilet begin           156
OFF Bed_to_Toilet end            154
OFF Wash_Dishes end               65
ON Wash_Dishes begin              65
ONc                               44
OFFc                              39
ON Housekeeping begin             33
OFF Housekeeping end              33
ON5                               17
ON Relax end                      14
OFF5                              14
OFFcc                              8
ON Meal_Preparation end            7
ON Respirate begin                 6
OFF Respirate end                  6
OFF5c                              6
ON Enter_Home begin                5
ON5c                               5
OFF Leave_Home end                 5
ONcc                               5
ON Sleeping end                    4
OFF Sleeping begin                 3
ON Work end                        3
ON Eating end                      3
ON Bed_to_Toilet end               3
OFcF                               3
OFF Relax begin                    3
ONc5c                              2
OFF5cc                             2
OFF Meal_Preparation begin         2
ONc5                               2
ON Leave_Home begin                2
ONM026                             2
OFFc5                              2
ON55                               1
OFF Bed_to_Toilet begin            1
ON Leave_Home end                  1
OcFF                               1
OFF Enter_Home end                 1
OFFccc5                            1
O Relax begin                      1
OFF Leave_Home begin               1
OF Meal_Preparation end            1
OFF Eating begin                   1
ONM009                             1
ONM024                             1
Name: count, dtype: int64

In [105]:
def extract_activity(value):
    value = str(value).strip()

    if " begin" in value:
        activity = value.replace("ON ", "").replace("OFF ", "").replace(" begin", "")
        return activity

    elif " end" in value:
        activity = value.replace("ON ", "").replace("OFF ", "").replace(" end", "")
        return activity

    return None


def extract_state(value):
    value = str(value).strip()

    if " begin" in value:
        return "begin"

    elif " end" in value:
        return "end"

    return None


df["activity_label"] = df["value"].apply(extract_activity)
df["activity_state"] = df["value"].apply(extract_state)

In [106]:
df.head(50)

,date,time,sensor,value,timestamp,sensor_type,hour,time_period,activity_label,activity_state
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M,0,night,Sleeping,begin
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M,0,night,None,None
15,2010-11-04,02:32:33.351906,M003,ON,2010-11-04 02:32:33.351906,M,2,night,None,None
16,2010-11-04,02:32:38.895958,M003,OFF,2010-11-04 02:32:38.895958,M,2,night,None,None
20,2010-11-04,03:42:21.82365,M003,ON,2010-11-04 03:42:21.823650,M,3,night,None,None
22,2010-11-04,03:42:25.93973,M003,OFF,2010-11-04 03:42:25.939730,M,3,night,None,None
23,2010-11-04,03:49:52.412755,M003,ON,2010-11-04 03:49:52.412755,M,3,night,None,None
24,2010-11-04,03:49:57.473649,M003,OFF,2010-11-04 03:49:57.473649,M,3,night,None,None
27,2010-11-04,04:14:32.835757,M003,ON,2010-11-04 04:14:32.835757,M,4,night,None,None
28,2010-11-04,04:14:33.203704,M002,ON,2010-11-04 04:14:33.203704,M,4,night,None,None
29,2010-11-04,04:14:37.15509,M002,OFF,2010-11-04 04:14:37.155090,M,4,night,None,None
30,2010-11-04,04:14:39.470621,M003,OFF,2010-11-04 04:14:39.470621,M,4,night,None,None
32,2010-11-04,04:34:17.62167,M003,ON,2010-11-04 04:34:17.621670,M,4,night,None,None
33,2010-11-04,04:34:19.224926,M002,ON,2010-11-04 04:34:19.224926,M,4,night,None,None
34,2010-11-04,04:34:20.849595,M002,OFF,2010-11-04 04:34:20.849595,M,4,night,None,None
35,2010-11-04,04:34:21.407224,M003,OFF,2010-11-04 04:34:21.407224,M,4,night,None,None
40,2010-11-04,05:40:27.708148,M003,ON,2010-11-04 05:40:27.708148,M,5,morning,None,None
41,2010-11-04,05:40:29.816524,M002,ON,2010-11-04 05:40:29.816524,M,5,morning,None,None
42,2010-11-04,05:40:32.342225,M007,ON,2010-11-04 05:40:32.342225,M,5,morning,None,None
43,2010-11-04,05:40:33.109478,M002,OFF,2010-11-04 05:40:33.109478,M,5,morning,None,None
44,2010-11-04,05:40:34.522278,M007,OFF,2010-11-04 05:40:34.522278,M,5,morning,None,None
45,2010-11-04,05:40:40.482626,M003,OFF,2010-11-04 05:40:40.482626,M,5,morning,None,None
46,2010-11-04,05:40:40.844463,M003,ON,2010-11-04 05:40:40.844463,M,5,morning,None,None
47,2010-11-04,05:40:42.452746,M007,ON,2010-11-04 05:40:42.452746,M,5,morning,None,None
48,2010-11-04,05:40:43.642664,M003,OFF Sleeping end,2010-11-04 05:40:43.642664,M,5,morning,Sleeping,end
49,2010-11-04,05:40:44.223548,M003,ON,2010-11-04 05:40:44.223548,M,5,morning,None,None
50,2010-11-04,05:40:45.939846,M005,ON,2010-11-04 05:40:45.939846,M,5,morning,None,None
51,2010-11-04,05:40:46.310862,M003,OFF,2010-11-04 05:40:46.310862,M,5,morning,None,None
52,2010-11-04,05:40:51.303739,M004,ON Bed_to_Toilet begin,2010-11-04 05:40:51.303739,M,5,morning,Bed_to_Toilet,begin
53,2010-11-04,05:40:52.342105,M005,OFF,2010-11-04 05:40:52.342105,M,5,morning,None,None
54,2010-11-04,05:40:57.176409,M007,OFF,2010-11-04 05:40:57.176409,M,5,morning,None,None
55,2010-11-04,05:40:57.941486,M004,OFF,2010-11-04 05:40:57.941486,M,5,morning,None,None
56,2010-11-04,05:43:24.021475,M004,ON,2010-11-04 05:43:24.021475,M,5,morning,None,None
57,2010-11-04,05:43:26.273181,M004,OFF,2010-11-04 05:43:26.273181,M,5,morning,None,None
58,2010-11-04,05:43:26.345503,M007,ON,2010-11-04 05:43:26.345503,M,5,morning,None,None
59,2010-11-04,05:43:26.793102,M004,ON,2010-11-04 05:43:26.793102,M,5,morning,None,None
60,2010-11-04,05:43:27.195347,M007,OFF,2010-11-04 05:43:27.195347,M,5,morning,None,None
61,2010-11-04,05:43:27.787437,M007,ON,2010-11-04 05:43:27.787437,M,5,morning,None,None
62,2010-11-04,05:43:29.711796,M005,ON,2010-11-04 05:43:29.711796,M,5,morning,None,None
63,2010-11-04,05:43:30.279021,M004,OFF Bed_to_Toilet end,2010-11-04 05:43:30.279021,M,5,morning,Bed_to_Toilet,end
64,2010-11-04,05:43:34.261135,M005,OFF,2010-11-04 05:43:34.261135,M,5,morning,None,None
65,2010-11-04,05:43:35.941892,M007,OFF,2010-11-04 05:43:35.941892,M,5,morning,None,None
66,2010-11-04,05:43:40.821615,M007,ON,2010-11-04 05:43:40.821615,M,5,morning,None,None
67,2010-11-04,05:43:45.619681,M007,OFF,2010-11-04 05:43:45.619681,M,5,morning,None,None
68,2010-11-04,05:43:45.7324,M003,ON Sleeping begin,2010-11-04 05:43:45.732400,M,5,morning,Sleeping,begin
69,2010-11-04,05:43:52.044085,M003,OFF,2010-11-04 05:43:52.044085,M,5,morning,None,None
70,2010-11-04,05:43:53.185335,M002,ON,2010-11-04 05:43:53.185335,M,5,morning,None,None
71,2010-11-04,05:43:53.253809,M003,ON,2010-11-04 05:43:53.253809,M,5,morning,None,None
72,2010-11-04,05:43:59.493281,M002,OFF,2010-11-04 05:43:59.493281,M,5,morning,None,None
73,2010-11-04,05:44:04.048766,M003,OFF,2010-11-04 05:44:04.048766,M,5,morning,None,None

In [107]:
print(df["activity_label"].value_counts(dropna=False))

activity_label
None                   1590033
Relax                     5837
Meal_Preparation          3211
Sleeping                   801
Eating                     514
CLOSE Enter_Home           431
OPEN Leave_Home            427
CLOSE Leave_Home           426
OPEN Enter_Home            425
Work                       342
Bed_to_Toilet              314
Wash_Dishes                130
Housekeeping                66
Respirate                   12
Leave_Home                   9
Enter_Home                   6
O Relax                      1
OF Meal_Preparation          1
Name: count, dtype: int64

In [108]:
df["timestamp"] = pd.to_datetime(df["timestamp"])

In [109]:
activity_df = df[df["activity_label"].notna()].copy()

In [110]:
activity_df = activity_df.sort_values("timestamp")

In [111]:
activities = []

for activity, group in activity_df.groupby("activity_label"):

    group = group.sort_values("timestamp")

    start_time = None

    for _, row in group.iterrows():

        if row["activity_state"] == "begin":
            start_time = row["timestamp"]

        elif row["activity_state"] == "end" and start_time is not None:

            end_time = row["timestamp"]

            duration = end_time - start_time

            activities.append({
                "activity": activity,
                "start": start_time,
                "end": end_time,
                "duration": duration
            })

            start_time = None

In [112]:
activity_duration_df = pd.DataFrame(activities)

In [113]:
print(activity_duration_df.head(30))

         activity                      start                        end  \
0   Bed_to_Toilet 2010-11-04 05:40:51.303739 2010-11-04 05:43:30.279021
1   Bed_to_Toilet 2010-11-05 04:18:09.406239 2010-11-05 04:20:50.109684
2   Bed_to_Toilet 2010-11-06 04:23:50.544193 2010-11-06 04:27:00.048965
3   Bed_to_Toilet 2010-11-07 00:34:48.871659 2010-11-07 00:35:36.223000
4   Bed_to_Toilet 2010-11-07 03:43:19.802838 2010-11-07 03:46:23.886632
5   Bed_to_Toilet 2010-11-07 03:49:20.647413 2010-11-07 03:51:17.964123
6   Bed_to_Toilet 2010-11-08 05:40:10.556874 2010-11-08 05:43:15.104099
7   Bed_to_Toilet 2010-11-09 00:30:32.314798 2010-11-09 00:32:54.868485
8   Bed_to_Toilet 2010-11-09 05:31:30.888221 2010-11-09 05:34:08.785188
9   Bed_to_Toilet 2010-11-11 05:13:58.821109 2010-11-11 05:16:28.261014
10  Bed_to_Toilet 2010-11-12 04:31:41.818859 2010-11-12 04:35:07.429031
11  Bed_to_Toilet 2010-11-13 05:17:05.045679 2010-11-13 05:20:52.478511
12  Bed_to_Toilet 2010-11-15 05:32:17.493645 2010-11-15 05:35:44.973115
13  Bed_to_Toilet 2010-11-16 00:37:28.060166 2010-11-16 00:39:25.601099
14  Bed_to_Toilet 2010-11-17 00:24:31.616930 2010-11-17 00:25:21.633567
15  Bed_to_Toilet 2010-11-17 02:58:56.283216 2010-11-17 03:01:58.145534
16  Bed_to_Toilet 2010-11-18 05:39:30.235604 2010-11-18 05:43:50.779600
17  Bed_to_Toilet 2010-11-20 00:36:14.715188 2010-11-20 00:37:05.903139
18  Bed_to_Toilet 2010-11-20 03:31:23.569485 2010-11-20 03:34:38.579317
19  Bed_to_Toilet 2010-11-21 00:17:52.486717 2010-11-21 00:21:09.771305
20  Bed_to_Toilet 2010-11-21 22:19:38.516703 2010-11-21 22:20:53.075808
21  Bed_to_Toilet 2010-11-22 05:44:20.244593 2010-11-22 05:47:35.208851
22  Bed_to_Toilet 2010-11-23 05:53:46.610096 2010-11-23 05:56:51.208908
23  Bed_to_Toilet 2010-11-24 00:37:30.531518 2010-11-24 00:40:06.451482
24  Bed_to_Toilet 2010-11-24 05:39:29.079102 2010-11-24 05:42:12.092995
25  Bed_to_Toilet 2010-11-25 00:48:28.990680 2010-11-25 00:51:35.047940
26  Bed_to_Toilet 2010-11-25 05:42:07.478061 2010-11-25 05:45:23.989755
27  Bed_to_Toilet 2010-11-26 05:51:54.349494 2010-11-26 05:55:29.629720
28  Bed_to_Toilet 2010-11-27 05:24:28.031033 2010-11-27 05:28:37.699942
29  Bed_to_Toilet 2010-11-27 23:44:41.585013 2010-11-27 23:45:51.790310

                 duration
0  0 days 00:02:38.975282
1  0 days 00:02:40.703445
2  0 days 00:03:09.504772
3  0 days 00:00:47.351341
4  0 days 00:03:04.083794
5  0 days 00:01:57.316710
6  0 days 00:03:04.547225
7  0 days 00:02:22.553687
8  0 days 00:02:37.896967
9  0 days 00:02:29.439905
10 0 days 00:03:25.610172
11 0 days 00:03:47.432832
12 0 days 00:03:27.479470
13 0 days 00:01:57.540933
14 0 days 00:00:50.016637
15 0 days 00:03:01.862318
16 0 days 00:04:20.543996
17 0 days 00:00:51.187951
18 0 days 00:03:15.009832
19 0 days 00:03:17.284588
20 0 days 00:01:14.559105
21 0 days 00:03:14.964258
22 0 days 00:03:04.598812
23 0 days 00:02:35.919964
24 0 days 00:02:43.013893
25 0 days 00:03:06.057260
26 0 days 00:03:16.511694
27 0 days 00:03:35.280226
28 0 days 00:04:09.668909
29 0 days 00:01:10.205297

In [114]:
activity_duration_df["duration_minutes"] = (
    activity_duration_df["duration"].dt.total_seconds() / 60
)

In [115]:
sleeping = activity_duration_df[
    activity_duration_df["activity"] == "Sleeping"
].copy()

print(sleeping.head(20))

      activity                      start                        end  \
4956  Sleeping 2010-11-04 00:03:50.209589 2010-11-04 05:40:43.642664
4957  Sleeping 2010-11-04 05:43:45.732400 2010-11-04 08:01:12.282970
4958  Sleeping 2010-11-05 00:00:11.187975 2010-11-05 04:18:05.416805
4959  Sleeping 2010-11-05 04:21:04.241472 2010-11-05 07:48:11.449954
4960  Sleeping 2010-11-05 22:48:22.713829 2010-11-06 04:23:40.440892
4961  Sleeping 2010-11-06 04:27:34.658690 2010-11-06 08:57:49.832587
4962  Sleeping 2010-11-07 00:02:39.008130 2010-11-07 00:34:46.642929
4963  Sleeping 2010-11-07 00:36:18.148567 2010-11-07 03:43:08.414022
4964  Sleeping 2010-11-07 03:46:41.571929 2010-11-07 03:47:14.894366
4965  Sleeping 2010-11-07 03:51:21.614944 2010-11-07 07:34:57.814105
4966  Sleeping 2010-11-07 23:52:03.472616 2010-11-08 05:39:57.034884
4967  Sleeping 2010-11-08 05:43:34.195173 2010-11-08 08:06:37.384531
4968  Sleeping 2010-11-08 23:54:38.878674 2010-11-09 00:30:28.196151
4969  Sleeping 2010-11-09 00:33:12.725408 2010-11-09 05:31:19.687641
4970  Sleeping 2010-11-09 05:34:57.482141 2010-11-09 08:39:58.539925
4971  Sleeping 2010-11-09 23:58:54.632904 2010-11-10 00:00:05.651914
4972  Sleeping 2010-11-10 00:09:31.789028 2010-11-10 06:41:22.490407
4973  Sleeping 2010-11-10 23:27:01.311306 2010-11-11 05:13:53.861830
4974  Sleeping 2010-11-11 05:16:35.591647 2010-11-11 08:40:02.470947
4975  Sleeping 2010-11-11 22:40:27.732760 2010-11-12 04:31:34.826655

                   duration  duration_minutes
4956 0 days 05:36:53.433075        336.890551
4957 0 days 02:17:26.550570        137.442509
4958 0 days 04:17:54.228830        257.903814
4959 0 days 03:27:07.208482        207.120141
4960 0 days 05:35:17.727063        335.295451
4961 0 days 04:30:15.173897        270.252898
4962 0 days 00:32:07.634799         32.127247
4963 0 days 03:06:50.265455        186.837758
4964 0 days 00:00:33.322437          0.555374
4965 0 days 03:43:36.199161        223.603319
4966 0 days 05:47:53.562268        347.892704
4967 0 days 02:23:03.189358        143.053156
4968 0 days 00:35:49.317477         35.821958
4969 0 days 04:58:06.962233        298.116037
4970 0 days 03:05:01.057784        185.017630
4971 0 days 00:01:11.019010          1.183650
4972 0 days 06:31:50.701379        391.845023
4973 0 days 05:46:52.550524        346.875842
4974 0 days 03:23:26.879300        203.447988
4975 0 days 05:51:07.093895        351.118232

In [116]:
print("Average sleep:",
      sleeping["duration_minutes"].mean(), "minutes")

print("Minimum sleep:",
      sleeping["duration_minutes"].min(), "minutes")

print("Maximum sleep:",
      sleeping["duration_minutes"].max(), "minutes")

Average sleep: 241.21442460902605 minutes
Minimum sleep: 0.55537395 minutes
Maximum sleep: 646.3969485 minutes

In [117]:
toilet = activity_duration_df[
    activity_duration_df["activity"] == "Bed_to_Toilet"
].copy()

print("Average Bed-to-Toilet:",
      toilet["duration_minutes"].mean(), "minutes")

print("Minimum Bed-to-Toilet:",
      toilet["duration_minutes"].min(), "minutes")

print("Maximum Bed-to-Toilet:",
      toilet["duration_minutes"].max(), "minutes")

Average Bed-to-Toilet: 2.7294809693376068 minutes
Minimum Bed-to-Toilet: 0.35722193333333335 minutes
Maximum Bed-to-Toilet: 8.702630333333333 minutes

In [118]:
print(
    activity_duration_df[
        ["activity", "start", "end", "duration_minutes"]
    ].to_string(index=False)
)

        activity                      start                        end  duration_minutes
   Bed_to_Toilet 2010-11-04 05:40:51.303739 2010-11-04 05:43:30.279021          2.649588
   Bed_to_Toilet 2010-11-05 04:18:09.406239 2010-11-05 04:20:50.109684          2.678391
   Bed_to_Toilet 2010-11-06 04:23:50.544193 2010-11-06 04:27:00.048965          3.158413
   Bed_to_Toilet 2010-11-07 00:34:48.871659 2010-11-07 00:35:36.223000          0.789189
   Bed_to_Toilet 2010-11-07 03:43:19.802838 2010-11-07 03:46:23.886632          3.068063
   Bed_to_Toilet 2010-11-07 03:49:20.647413 2010-11-07 03:51:17.964123          1.955278
   Bed_to_Toilet 2010-11-08 05:40:10.556874 2010-11-08 05:43:15.104099          3.075787
   Bed_to_Toilet 2010-11-09 00:30:32.314798 2010-11-09 00:32:54.868485          2.375895
   Bed_to_Toilet 2010-11-09 05:31:30.888221 2010-11-09 05:34:08.785188          2.631616
   Bed_to_Toilet 2010-11-11 05:13:58.821109 2010-11-11 05:16:28.261014          2.490665
   Bed_to_Toilet 2010-11-12 04:31:41.818859 2010-11-12 04:35:07.429031          3.426836
   Bed_to_Toilet 2010-11-13 05:17:05.045679 2010-11-13 05:20:52.478511          3.790547
   Bed_to_Toilet 2010-11-15 05:32:17.493645 2010-11-15 05:35:44.973115          3.457991
   Bed_to_Toilet 2010-11-16 00:37:28.060166 2010-11-16 00:39:25.601099          1.959016
   Bed_to_Toilet 2010-11-17 00:24:31.616930 2010-11-17 00:25:21.633567          0.833611
   Bed_to_Toilet 2010-11-17 02:58:56.283216 2010-11-17 03:01:58.145534          3.031039
   Bed_to_Toilet 2010-11-18 05:39:30.235604 2010-11-18 05:43:50.779600          4.342400
   Bed_to_Toilet 2010-11-20 00:36:14.715188 2010-11-20 00:37:05.903139          0.853133
   Bed_to_Toilet 2010-11-20 03:31:23.569485 2010-11-20 03:34:38.579317          3.250164
   Bed_to_Toilet 2010-11-21 00:17:52.486717 2010-11-21 00:21:09.771305          3.288076
   Bed_to_Toilet 2010-11-21 22:19:38.516703 2010-11-21 22:20:53.075808          1.242652
   Bed_to_Toilet 2010-11-22 05:44:20.244593 2010-11-22 05:47:35.208851          3.249404
   Bed_to_Toilet 2010-11-23 05:53:46.610096 2010-11-23 05:56:51.208908          3.076647
   Bed_to_Toilet 2010-11-24 00:37:30.531518 2010-11-24 00:40:06.451482          2.598666
   Bed_to_Toilet 2010-11-24 05:39:29.079102 2010-11-24 05:42:12.092995          2.716898
   Bed_to_Toilet 2010-11-25 00:48:28.990680 2010-11-25 00:51:35.047940          3.100954
   Bed_to_Toilet 2010-11-25 05:42:07.478061 2010-11-25 05:45:23.989755          3.275195
   Bed_to_Toilet 2010-11-26 05:51:54.349494 2010-11-26 05:55:29.629720          3.588004
   Bed_to_Toilet 2010-11-27 05:24:28.031033 2010-11-27 05:28:37.699942          4.161148
   Bed_to_Toilet 2010-11-27 23:44:41.585013 2010-11-27 23:45:51.790310          1.170088
   Bed_to_Toilet 2010-11-28 05:21:15.685275 2010-11-28 05:24:58.548113          3.714381
   Bed_to_Toilet 2010-11-29 01:38:51.469559 2010-11-29 01:39:31.011821          0.659038
   Bed_to_Toilet 2010-11-30 00:39:09.024296 2010-11-30 00:40:14.176605          1.085872
   Bed_to_Toilet 2010-11-30 06:03:43.446509 2010-11-30 06:06:26.452756          2.716771
   Bed_to_Toilet 2010-12-02 04:32:00.652119 2010-12-02 04:36:11.257836          4.176762
   Bed_to_Toilet 2010-12-03 00:40:01.592953 2010-12-03 00:42:32.452135          2.514320
   Bed_to_Toilet 2010-12-04 07:32:11.073465 2010-12-04 07:36:05.631460          3.909300
   Bed_to_Toilet 2010-12-04 22:59:25.891931 2010-12-04 23:01:10.902644          1.750179
   Bed_to_Toilet 2010-12-05 04:35:45.273022 2010-12-05 04:39:03.883315          3.310172
   Bed_to_Toilet 2010-12-06 04:19:01.362514 2010-12-06 04:22:01.392512          3.000500
   Bed_to_Toilet 2010-12-07 00:20:52.010563 2010-12-07 00:23:13.659864          2.360822
   Bed_to_Toilet 2010-12-07 05:15:20.582769 2010-12-07 05:17:52.033103          2.524172
   Bed_to_Toilet 2010-12-08 04:05:18.796797 2010-12-08 04:07:51.277149          2.541339
   Bed_to_Toilet 2010-12-09 03:09:22.532479 2010-12-09 03:12:24.654381          3.035365
   Bed_to_Toilet 2010-12-11 23:43:36.097306 2010-12-11 23:46:32.287586          2.936505
   Bed_to_Toilet 2010-12-12 03:47:32.464322 2010-12-12 03:50:36.912847          3.074142
   Bed_to_Toilet 2010-12-13 03:03:43.704985 2010-12-13 03:06:48.063366          3.072640
   Bed_to_Toilet 2010-12-14 06:20:16.680011 2010-12-14 06:23:38.649685          3.366161
   Bed_to_Toilet 2010-12-15 00:42:08.555409 2010-12-15 00:43:03.990217          0.923913
   Bed_to_Toilet 2010-12-15 05:13:10.475089 2010-12-15 05:16:21.351492          3.181273
   Bed_to_Toilet 2010-12-17 06:06:47.677515 2010-12-17 06:09:26.765231          2.651462
   Bed_to_Toilet 2010-12-18 01:27:46.413229 2010-12-18 01:28:30.480940          0.734462
   Bed_to_Toilet 2010-12-18 07:05:14.404894 2010-12-18 07:07:45.804895          2.523333
   Bed_to_Toilet 2010-12-19 07:23:35.812732 2010-12-19 07:28:15.810557          4.666630
   Bed_to_Toilet 2010-12-20 00:23:53.224370 2010-12-20 00:24:14.657686          0.357222
   Bed_to_Toilet 2010-12-20 05:13:03.087978 2010-12-20 05:17:22.559569          4.324527
   Bed_to_Toilet 2010-12-22 00:54:20.568136 2010-12-22 00:55:07.196247          0.777135
   Bed_to_Toilet 2010-12-22 06:07:45.871031 2010-12-22 06:11:18.361483          3.541508
   Bed_to_Toilet 2010-12-23 00:31:16.933842 2010-12-23 00:32:53.167850          1.603900
   Bed_to_Toilet 2010-12-23 00:33:20.613973 2010-12-23 00:34:16.011460          0.923291
   Bed_to_Toilet 2010-12-23 05:10:06.935119 2010-12-23 05:12:46.859771          2.665411
   Bed_to_Toilet 2010-12-24 03:22:37.364010 2010-12-24 03:25:13.181202          2.596953
   Bed_to_Toilet 2010-12-26 04:54:15.425101 2010-12-26 05:00:57.135802          6.695178
   Bed_to_Toilet 2010-12-29 04:24:15.699653 2010-12-29 04:26:47.921024          2.537023
   Bed_to_Toilet 2011-01-01 06:15:55.528866 2011-01-01 06:18:23.293976          2.462752
   Bed_to_Toilet 2011-01-02 05:42:42.581676 2011-01-02 05:45:15.185803          2.543402
   Bed_to_Toilet 2011-01-04 08:08:10.376220 2011-01-04 08:11:31.612815          3.353943
   Bed_to_Toilet 2011-01-05 05:54:23.582746 2011-01-05 05:56:58.903017          2.588671
   Bed_to_Toilet 2011-01-07 07:15:23.726204 2011-01-07 07:18:47.609036          3.398047
   Bed_to_Toilet 2011-01-08 05:50:03.391941 2011-01-08 05:53:16.924063          3.225535
   Bed_to_Toilet 2011-01-09 05:30:45.822447 2011-01-09 05:34:00.497681          3.244587
   Bed_to_Toilet 2011-01-10 04:05:53.043100 2011-01-10 04:08:53.515633          3.007876
   Bed_to_Toilet 2011-01-11 06:06:48.906446 2011-01-11 06:10:18.398057          3.491527
   Bed_to_Toilet 2011-01-14 05:37:44.803408 2011-01-14 05:40:22.929663          2.635438
   Bed_to_Toilet 2011-01-15 05:45:02.511422 2011-01-15 05:48:04.331058          3.030327
   Bed_to_Toilet 2011-01-17 04:54:43.686795 2011-01-17 04:58:52.700297          4.150225
   Bed_to_Toilet 2011-01-18 06:05:51.510629 2011-01-18 06:08:01.585627          2.167917
   Bed_to_Toilet 2011-01-18 06:08:47.087140 2011-01-18 06:09:37.778618          0.844858
   Bed_to_Toilet 2011-01-19 04:25:10.315975 2011-01-19 04:27:22.261412          2.199091
   Bed_to_Toilet 2011-01-22 05:56:22.171984 2011-01-22 05:59:45.197317          3.383756
   Bed_to_Toilet 2011-01-29 05:09:11.089119 2011-01-29 05:12:00.692764          2.826727
   Bed_to_Toilet 2011-01-31 03:42:13.017228 2011-01-31 03:45:07.908763          2.914859
   Bed_to_Toilet 2011-02-01 05:31:29.084399 2011-02-01 05:34:16.361110          2.787945
   Bed_to_Toilet 2011-02-02 03:28:23.426337 2011-02-02 03:32:42.365794          4.315658
   Bed_to_Toilet 2011-02-04 04:09:11.894624 2011-02-04 04:12:32.611218          3.345277
   Bed_to_Toilet 2011-02-07 05:35:53.258784 2011-02-07 05:38:12.431531          2.319546
   Bed_to_Toilet 2011-02-08 05:46:50.932014 2011-02-08 05:53:06.683796          6.262530
   Bed_to_Toilet 2011-02-09 04:28:23.310502 2011-02-09 04:30:09.601723          1.771520
   Bed_to_Toilet 2011-02-12 04:33:33.984986 2011-02-12 04:37:23.682103          3.828285
   Bed_to_Toilet 2011-02-14 04:47:57.215610 2011-02-14 04:50:16.311895          2.318271
   Bed_to_Toilet 2011-02-15 05:05:23.859096 2011-02-15 05:07:37.829775          2.232845
   Bed_to_Toilet 2011-02-18 04:53:30.469980 2011-02-18 04:56:39.089000          3.143650
   Bed_to_Toilet 2011-02-19 04:41:23.712823 2011-02-19 04:44:20.040912          2.938801
   Bed_to_Toilet 2011-02-24 04:46:27.199839 2011-02-24 04:49:03.622207          2.607039
   Bed_to_Toilet 2011-02-28 05:15:03.003369 2011-02-28 05:17:24.566551          2.359386
   Bed_to_Toilet 2011-03-01 06:11:30.482775 2011-03-01 06:13:18.065286          1.793042
   Bed_to_Toilet 2011-03-02 04:33:27.110762 2011-03-02 04:36:08.360641          2.687498
   Bed_to_Toilet 2011-03-03 04:00:01.808178 2011-03-03 04:03:12.859052          3.184181
   Bed_to_Toilet 2011-03-04 04:36:07.195564 2011-03-04 04:38:17.287429          2.168198
   Bed_to_Toilet 2011-03-06 06:42:56.796980 2011-03-06 06:47:12.091737          4.254913
   Bed_to_Toilet 2011-03-07 05:13:24.718664 2011-03-07 05:16:01.938254          2.620327
   Bed_to_Toilet 2011-03-10 05:07:15.578842 2011-03-10 05:12:18.489567          5.048512
   Bed_to_Toilet 2011-03-14 07:03:26.581511 2011-03-14 07:05:54.632810          2.467522
   Bed_to_Toilet 2011-03-16 06:19:11.625693 2011-03-16 06:21:06.482796          1.914285
   Bed_to_Toilet 2011-03-19 04:58:24.337248 2011-03-19 05:01:26.581765          3.037409
   Bed_to_Toilet 2011-03-20 01:43:15.015306 2011-03-20 01:51:57.173126          8.702630
   Bed_to_Toilet 2011-03-20 03:02:14.513006 2011-03-20 03:03:54.353093          1.664001
   Bed_to_Toilet 2011-03-20 06:47:23.181828 2011-03-20 06:49:57.430130          2.570805
   Bed_to_Toilet 2011-03-21 02:25:17.080140 2011-03-21 02:27:02.595073          1.758582
   Bed_to_Toilet 2011-03-24 05:57:48.694715 2011-03-24 06:05:42.794442          7.901662
   Bed_to_Toilet 2011-03-27 03:53:26.374046 2011-03-27 03:55:33.117957          2.112399
   Bed_to_Toilet 2011-03-28 04:11:08.902716 2011-03-28 04:14:09.781942          3.014654
   Bed_to_Toilet 2011-03-30 01:19:33.379324 2011-03-30 01:20:02.504452          0.485419
   Bed_to_Toilet 2011-03-30 05:46:39.821124 2011-03-30 05:48:38.986891          1.986096
   Bed_to_Toilet 2011-03-31 04:46:09.726167 2011-03-31 04:49:50.349033          3.677048
   Bed_to_Toilet 2011-04-01 01:13:43.890020 2011-04-01 01:16:16.462383          2.542873
   Bed_to_Toilet 2011-04-05 04:26:30.962743 2011-04-05 04:30:15.330043          3.739455
   Bed_to_Toilet 2011-04-07 03:34:56.078326 2011-04-07 03:36:43.092209          1.783565
   Bed_to_Toilet 2011-04-07 06:51:47.419115 2011-04-07 06:54:08.669370          2.354171
   Bed_to_Toilet 2011-04-09 03:58:28.737500 2011-04-09 04:00:24.056473          1.921983
   Bed_to_Toilet 2011-04-10 04:21:52.775868 2011-04-10 04:25:10.921581          3.302429
   Bed_to_Toilet 2011-04-11 03:42:42.271394 2011-04-11 03:44:52.325913          2.167575
   Bed_to_Toilet 2011-04-13 04:36:29.638763 2011-04-13 04:38:33.449037          2.063505
   Bed_to_Toilet 2011-04-14 04:13:47.612756 2011-04-14 04:15:14.109326          1.441609
   Bed_to_Toilet 2011-04-15 03:21:06.658314 2011-04-15 03:23:30.072096          2.390230
   Bed_to_Toilet 2011-04-17 03:49:50.256888 2011-04-17 03:52:04.414671          2.235963
   Bed_to_Toilet 2011-04-18 05:45:32.688777 2011-04-18 05:47:32.503950          1.996920
   Bed_to_Toilet 2011-04-19 07:08:05.611567 2011-04-19 07:10:12.375557          2.112733
   Bed_to_Toilet 2011-04-20 04:59:31.664303 2011-04-20 05:01:26.286544          1.910371
   Bed_to_Toilet 2011-04-21 01:17:58.576530 2011-04-21 01:20:40.439749          2.697720
   Bed_to_Toilet 2011-04-22 06:01:18.583238 2011-04-22 06:03:17.023721          1.974008
   Bed_to_Toilet 2011-04-23 05:01:48.021547 2011-04-23 05:03:26.146598          1.635418
   Bed_to_Toilet 2011-04-29 01:45:00.789311 2011-04-29 01:47:12.897250          2.201799
   Bed_to_Toilet 2011-05-01 02:47:38.464391 2011-05-01 02:50:08.138062          2.494561
   Bed_to_Toilet 2011-05-03 03:31:29.728755 2011-05-03 03:33:09.268982          1.659004
   Bed_to_Toilet 2011-05-08 03:31:20.930890 2011-05-08 03:33:30.945033          2.166902
   Bed_to_Toilet 2011-05-10 03:31:27.583054 2011-05-10 03:33:39.430967          2.197465
   Bed_to_Toilet 2011-05-12 03:39:05.573548 2011-05-12 03:41:02.252265          1.944645
   Bed_to_Toilet 2011-05-13 04:01:59.407241 2011-05-13 04:04:32.406893          2.549994
   Bed_to_Toilet 2011-05-14 04:40:16.670114 2011-05-14 04:42:55.487404          2.646955
   Bed_to_Toilet 2011-05-15 04:22:50.398987 2011-05-15 04:25:50.590135          3.003186
   Bed_to_Toilet 2011-05-19 04:08:30.061901 2011-05-19 04:11:39.480842          3.156982
   Bed_to_Toilet 2011-05-22 02:34:51.206085 2011-05-22 02:38:08.944841          3.295646
   Bed_to_Toilet 2011-05-23 02:43:48.915537 2011-05-23 02:46:50.952736          3.033953
   Bed_to_Toilet 2011-05-25 03:06:42.155540 2011-05-25 03:08:38.620115          1.941076
   Bed_to_Toilet 2011-05-27 04:41:18.690933 2011-05-27 04:43:18.105710          1.990246
   Bed_to_Toilet 2011-05-29 03:33:19.045003 2011-05-29 03:35:27.396978          2.139200
   Bed_to_Toilet 2011-05-30 02:32:47.689839 2011-05-30 02:34:59.378419          2.194810
   Bed_to_Toilet 2011-05-31 04:02:29.953621 2011-05-31 04:04:31.523469          2.026164
   Bed_to_Toilet 2011-06-02 03:56:11.192200 2011-06-02 03:58:08.579498          1.956455
   Bed_to_Toilet 2011-06-03 02:50:28.222282 2011-06-03 02:53:20.552687          2.872173
   Bed_to_Toilet 2011-06-05 03:46:10.078230 2011-06-05 03:48:29.864856          2.329777
   Bed_to_Toilet 2011-06-06 01:38:28.634181 2011-06-06 01:41:39.310919          3.177946
   Bed_to_Toilet 2011-06-07 03:33:43.093879 2011-06-07 03:36:13.028123          2.498904
   Bed_to_Toilet 2011-06-08 02:53:30.864259 2011-06-08 02:56:26.062986          2.919979
   Bed_to_Toilet 2011-06-09 02:04:48.336353 2011-06-09 02:09:26.987949          4.644193
CLOSE Enter_Home 2011-01-12 20:38:34.735610 2011-01-13 10:28:18.024088        829.721475
CLOSE Leave_Home 2011-03-03 08:28:28.319905 2011-03-03 15:40:13.294622        431.749579
          Eating 2010-11-04 09:56:41.831135 2010-11-04 09:59:04.438334          2.376787
          Eating 2010-11-04 09:59:47.894921 2010-11-04 10:02:48.972200          3.017955
          Eating 2010-11-04 15:25:35.233346 2010-11-04 15:28:42.550415          3.121951
          Eating 2010-11-04 17:35:16.153016 2010-11-04 17:37:11.693732          1.925679
          Eating 2010-11-05 16:25:44.067607 2010-11-05 16:29:13.880311          3.496878
          Eating 2010-11-06 09:28:19.566626 2010-11-06 09:37:40.974527          9.356798
          Eating 2010-11-06 12:02:29.411879 2010-11-06 12:09:53.753134          7.405688
          Eating 2010-11-06 12:35:50.690281 2010-11-06 12:49:00.074717         13.156407
          Eating 2010-11-07 08:06:14.168036 2010-11-07 08:13:27.570571          7.223376
          Eating 2010-11-07 12:08:27.137756 2010-11-07 12:20:17.842926         11.845086
          Eating 2010-11-07 12:24:27.722796 2010-11-07 12:30:34.879404          6.119277
          Eating 2010-11-07 12:38:28.188402 2010-11-07 12:54:59.342931         16.519242
          Eating 2010-11-07 14:40:39.524104 2010-11-07 14:42:49.951552          2.173791
          Eating 2010-11-07 15:10:28.466169 2010-11-07 15:13:19.302832          2.847278
          Eating 2010-11-07 15:42:09.462097 2010-11-07 15:55:52.961299         13.724987
          Eating 2010-11-07 17:07:54.817874 2010-11-07 17:12:21.378391          4.442675
          Eating 2010-11-07 17:30:26.962074 2010-11-07 17:40:44.680561         10.295308
          Eating 2010-11-07 20:37:41.433566 2010-11-07 20:40:22.031282          2.676629
          Eating 2010-11-08 10:03:57.812263 2010-11-08 10:25:05.916114         21.135064
          Eating 2010-11-08 10:28:50.009598 2010-11-08 10:38:29.221668          9.653535
          Eating 2010-11-08 11:28:52.984094 2010-11-08 11:31:46.985583          2.900025
          Eating 2010-11-08 14:06:15.423694 2010-11-08 14:16:31.421845         10.266636
          Eating 2010-11-08 18:45:02.388028 2010-11-08 18:54:49.472404          9.784740
          Eating 2010-11-09 13:47:37.712245 2010-11-09 13:53:41.466364          6.062569
          Eating 2010-11-09 14:00:12.325108 2010-11-09 14:08:35.143155          8.380301
          Eating 2010-11-09 18:06:45.636065 2010-11-09 18:10:01.352728          3.261944
          Eating 2010-11-09 18:12:17.289050 2010-11-09 18:20:02.683192          7.756569
          Eating 2010-11-09 18:22:50.176141 2010-11-09 18:25:57.625503          3.124156
          Eating 2010-11-09 18:31:42.423873 2010-11-09 18:39:35.772777          7.889148
          Eating 2010-11-09 18:55:41.623343 2010-11-09 19:01:21.911490          5.671469
          Eating 2010-11-10 09:23:09.800579 2010-11-10 09:29:04.902663          5.918368
          Eating 2010-11-10 18:28:50.456987 2010-11-10 18:34:32.065480          5.693475
          Eating 2010-11-10 18:42:54.092155 2010-11-10 18:53:30.347313         10.604253
          Eating 2010-11-11 10:07:37.847335 2010-11-11 10:13:37.640651          5.996555
          Eating 2010-11-11 13:44:19.019213 2010-11-11 13:52:16.239233          7.953667
          Eating 2010-11-11 22:10:59.689887 2010-11-11 22:15:33.310120          4.560337
          Eating 2010-11-11 22:17:08.882465 2010-11-11 22:24:14.708406          7.097099
          Eating 2010-11-12 10:37:55.724892 2010-11-12 10:42:58.504102          5.046320
          Eating 2010-11-12 13:51:36.817131 2010-11-12 14:03:02.763764         11.432444
          Eating 2010-11-12 16:45:34.509412 2010-11-12 16:54:33.155886          8.977441
          Eating 2010-11-13 14:06:25.247248 2010-11-13 14:14:19.830409          7.909719
          Eating 2010-11-13 19:07:47.783006 2010-11-13 19:20:03.301215         12.258637
          Eating 2010-11-14 06:28:35.055350 2010-11-14 06:36:26.137579          7.851370
          Eating 2010-11-15 15:08:40.603755 2010-11-15 15:29:48.449489         21.130762
          Eating 2010-11-15 15:31:00.519401 2010-11-15 15:39:41.718045          8.686644
          Eating 2010-11-15 19:31:35.680228 2010-11-15 19:39:29.360590          7.894673
          Eating 2010-11-16 09:52:59.200389 2010-11-16 10:03:23.142926         10.399042
          Eating 2010-11-17 07:20:47.136331 2010-11-17 07:22:18.630025          1.524895
          Eating 2010-11-17 19:18:14.206923 2010-11-17 19:35:24.284390         17.167958
          Eating 2010-11-18 19:42:34.001669 2010-11-18 20:03:01.983280         20.466360
          Eating 2010-11-18 20:42:38.177495 2010-11-18 21:01:38.469480         19.004866
          Eating 2010-11-19 10:01:18.532926 2010-11-19 10:19:23.272462         18.078992
          Eating 2010-11-20 09:46:33.781376 2010-11-20 09:54:06.571282          7.546498
          Eating 2010-11-20 13:50:30.904830 2010-11-20 14:36:35.642935         46.078968
          Eating 2010-11-22 09:26:40.253001 2010-11-22 09:30:41.281301          4.017138
          Eating 2010-11-24 13:35:49.738754 2010-11-24 13:47:57.573626         12.130581
          Eating 2010-11-26 15:41:55.390534 2010-11-26 16:07:32.401299         25.616846
          Eating 2010-11-28 10:48:32.686639 2010-11-28 11:11:44.955369         23.204479
          Eating 2010-11-28 21:47:14.074734 2010-11-28 21:53:24.113710          6.167316
          Eating 2010-11-29 19:16:12.704749 2010-11-29 19:24:07.514023          7.913488
          Eating 2010-11-30 10:26:08.088902 2010-11-30 10:31:49.207822          5.685315
          Eating 2010-11-30 16:12:00.901638 2010-11-30 16:24:22.729236         12.363793
          Eating 2010-11-30 18:14:42.335545 2010-11-30 18:24:27.782935          9.757456
          Eating 2010-12-01 10:04:33.909291 2010-12-01 10:12:20.203536          7.771571
          Eating 2010-12-01 18:15:32.318848 2010-12-01 18:21:27.471503          5.919211

In [119]:
summary = (
    activity_duration_df
    .groupby("activity")["duration_minutes"]
    .agg(
        occurrences="count",
        total_minutes="sum",
        average_minutes="mean",
        minimum_minutes="min",
        maximum_minutes="max"
    )
    .reset_index()
)

print(summary)

            activity  occurrences  total_minutes  average_minutes  \
0      Bed_to_Toilet          156     425.799031         2.729481
1   CLOSE Enter_Home            1     829.721475       829.721475
2   CLOSE Leave_Home            1     431.749579       431.749579
3             Eating          255    2588.063293        10.149268
4         Enter_Home            1     391.872700       391.872700
5       Housekeeping           33     670.692592        20.324018
6         Leave_Home            2   15692.331538      7846.165769
7   Meal_Preparation         1595   12501.970885         7.838226
8              Relax         2906   97152.671763        33.431752
9          Respirate            6      51.385846         8.564308
10          Sleeping          397   95762.126570       241.214425
11       Wash_Dishes           64     463.752002         7.246125
12              Work          171    2920.759088        17.080463

    minimum_minutes  maximum_minutes
0          0.357222         8.702630
1        829.721475       829.721475
2        431.749579       431.749579
3          0.264641        69.475333
4        391.872700       391.872700
5          1.536077        90.010639
6          0.014001     15692.317537
7          0.126168       326.200545
8          0.944290       255.024874
9          1.638024        24.919531
10         0.555374       646.396949
11         0.554909        36.654173
12         0.913070       116.940938

In [120]:
print(df["sensor_type"].value_counts())

sensor_type
M    1596145
D       6836
L          4
E          1
Name: count, dtype: int64

In [121]:
df = df[df["sensor_type"].isin(["M", "D"])].copy()

In [122]:
df.to_csv("../aruba_cleaned.csv", index=False)