In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../aruba_cleaned.csv")
df

,date,time,sensor,value,timestamp,sensor_type,hour,time_period,activity_label,activity_state
0,2010-11-04,00:03:50.209589,M003,ON Sleeping begin,2010-11-04 00:03:50.209589,M,0,night,Sleeping,begin
1,2010-11-04,00:03:57.399391,M003,OFF,2010-11-04 00:03:57.399391,M,0,night,NaN,NaN
2,2010-11-04,02:32:33.351906,M003,ON,2010-11-04 02:32:33.351906,M,2,night,NaN,NaN
3,2010-11-04,02:32:38.895958,M003,OFF,2010-11-04 02:32:38.895958,M,2,night,NaN,NaN
4,2010-11-04,03:42:21.82365,M003,ON,2010-11-04 03:42:21.823650,M,3,night,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
1602976,2011-06-11,22:33:01.209214,M002,ON,2011-06-11 22:33:01.209214,M,22,night,NaN,NaN
1602977,2011-06-11,22:33:02.952009,M003,OFF,2011-06-11 22:33:02.952009,M,22,night,NaN,NaN
1602978,2011-06-11,22:33:03.332876,M002,OFF,2011-06-11 22:33:03.332876,M,22,night,NaN,NaN
1602979,2011-06-11,23:20:31.432636,M003,ON,2011-06-11 23:20:31.432636,M,23,night,NaN,NaN
1602980,2011-06-11,23:20:35.72238,M003,OFF,2011-06-11 23:20:35.722380,M,23,night,NaN,NaN

In [4]:
activities = df["activity_label"].dropna().unique()

print(activities)

['Sleeping' 'Bed_to_Toilet' 'Meal_Preparation' 'Relax' 'Housekeeping'
 'Eating' 'Wash_Dishes' 'OPEN Leave_Home' 'CLOSE Leave_Home'
 'OPEN Enter_Home' 'CLOSE Enter_Home' 'Work' 'Respirate' 'Leave_Home'
 'Enter_Home' 'O Relax' 'OF Meal_Preparation']

In [6]:
# Make sure timestamp is datetime
df["timestamp"] = pd.to_datetime(df["timestamp"])

# Keep only rows that have an activity
activity_df = df[df["activity_label"].notna()].copy()

# Sort by time
activity_df = activity_df.sort_values("timestamp")

activities = []

for activity, group in activity_df.groupby("activity_label"):
    
    group = group.sort_values("timestamp")
    start_time = None

    for _, row in group.iterrows():

        if row["activity_state"] == "begin":
            start_time = row["timestamp"]

        elif row["activity_state"] == "end" and start_time is not None:

            end_time = row["timestamp"]

            duration = end_time - start_time

            activities.append({
                "activity": activity,
                "start": start_time,
                "end": end_time,
                "duration": duration
            })

            start_time = None

# Create DataFrame
activity_duration_df = pd.DataFrame(activities)

# Convert duration to minutes
activity_duration_df["duration_minutes"] = (
    activity_duration_df["duration"].dt.total_seconds() / 60
)

print(activity_duration_df.head())

        activity                      start                        end  \
0  Bed_to_Toilet 2010-11-04 05:40:51.303739 2010-11-04 05:43:30.279021
1  Bed_to_Toilet 2010-11-05 04:18:09.406239 2010-11-05 04:20:50.109684
2  Bed_to_Toilet 2010-11-06 04:23:50.544193 2010-11-06 04:27:00.048965
3  Bed_to_Toilet 2010-11-07 00:34:48.871659 2010-11-07 00:35:36.223000
4  Bed_to_Toilet 2010-11-07 03:43:19.802838 2010-11-07 03:46:23.886632

                duration  duration_minutes
0 0 days 00:02:38.975282          2.649588
1 0 days 00:02:40.703445          2.678391
2 0 days 00:03:09.504772          3.158413
3 0 days 00:00:47.351341          0.789189
4 0 days 00:03:04.083794          3.068063

In [7]:
duration_summary = (
    activity_duration_df
    .groupby("activity")["duration_minutes"]
    .agg(
        average_duration="mean",
        min_duration="min",
        max_duration="max"
    )
    .reset_index()
)

print(duration_summary)

            activity  average_duration  min_duration  max_duration
0      Bed_to_Toilet          2.729481      0.357222      8.702630
1   CLOSE Enter_Home        829.721475    829.721475    829.721475
2   CLOSE Leave_Home        431.749579    431.749579    431.749579
3             Eating         10.149268      0.264641     69.475333
4         Enter_Home        391.872700    391.872700    391.872700
5       Housekeeping         20.324018      1.536077     90.010639
6         Leave_Home       7846.165769      0.014001  15692.317537
7   Meal_Preparation          7.838226      0.126168    326.200545
8              Relax         33.431752      0.944290    255.024874
9          Respirate          8.564308      1.638024     24.919531
10          Sleeping        241.214425      0.555374    646.396949
11       Wash_Dishes          7.246125      0.554909     36.654173
12              Work         17.080463      0.913070    116.940938

In [8]:
activity_counts = df["activity_label"].value_counts()

print(activity_counts)

activity_label
Relax                  5837
Meal_Preparation       3211
Sleeping                801
Eating                  514
CLOSE Enter_Home        431
OPEN Leave_Home         427
CLOSE Leave_Home        426
OPEN Enter_Home         425
Work                    342
Bed_to_Toilet           314
Wash_Dishes             130
Housekeeping             66
Respirate                12
Leave_Home                9
Enter_Home                6
O Relax                   1
OF Meal_Preparation       1
Name: count, dtype: int64

In [9]:
activities_to_remove = [
    "Respirate",
    "Leave_Home",
    "Enter_Home",
    "O Relax",
    "OF Meal_Preparation"
]

df = df[~df["activity_label"].isin(activities_to_remove)].copy()

In [10]:
activity_counts = df["activity_label"].value_counts()

print(activity_counts)

activity_label
Relax               5837
Meal_Preparation    3211
Sleeping             801
Eating               514
CLOSE Enter_Home     431
OPEN Leave_Home      427
CLOSE Leave_Home     426
OPEN Enter_Home      425
Work                 342
Bed_to_Toilet        314
Wash_Dishes          130
Housekeeping          66
Name: count, dtype: int64

In [11]:
duration_summary = (
    activity_duration_df
    .groupby("activity")["duration_minutes"]
    .agg(
        average_duration="mean",
        min_duration="min",
        max_duration="max"
    )
    .reset_index()
)

print(duration_summary)

            activity  average_duration  min_duration  max_duration
0      Bed_to_Toilet          2.729481      0.357222      8.702630
1   CLOSE Enter_Home        829.721475    829.721475    829.721475
2   CLOSE Leave_Home        431.749579    431.749579    431.749579
3             Eating         10.149268      0.264641     69.475333
4         Enter_Home        391.872700    391.872700    391.872700
5       Housekeeping         20.324018      1.536077     90.010639
6         Leave_Home       7846.165769      0.014001  15692.317537
7   Meal_Preparation          7.838226      0.126168    326.200545
8              Relax         33.431752      0.944290    255.024874
9          Respirate          8.564308      1.638024     24.919531
10          Sleeping        241.214425      0.555374    646.396949
11       Wash_Dishes          7.246125      0.554909     36.654173
12              Work         17.080463      0.913070    116.940938

In [14]:
activity_duration_df["date"] = activity_duration_df["start"].dt.date

activity_duration_df["hour"] = activity_duration_df["start"].dt.hour

activity_duration_df["minute"] = activity_duration_df["start"].dt.minute

activity_duration_df["day_of_week"] = (
    activity_duration_df["start"].dt.day_name()
)

activity_duration_df["start_time"] = (
    activity_duration_df["start"].dt.time
)

print(activity_duration_df.head(50))

         activity                      start                        end  \
0   Bed_to_Toilet 2010-11-04 05:40:51.303739 2010-11-04 05:43:30.279021
1   Bed_to_Toilet 2010-11-05 04:18:09.406239 2010-11-05 04:20:50.109684
2   Bed_to_Toilet 2010-11-06 04:23:50.544193 2010-11-06 04:27:00.048965
3   Bed_to_Toilet 2010-11-07 00:34:48.871659 2010-11-07 00:35:36.223000
4   Bed_to_Toilet 2010-11-07 03:43:19.802838 2010-11-07 03:46:23.886632
5   Bed_to_Toilet 2010-11-07 03:49:20.647413 2010-11-07 03:51:17.964123
6   Bed_to_Toilet 2010-11-08 05:40:10.556874 2010-11-08 05:43:15.104099
7   Bed_to_Toilet 2010-11-09 00:30:32.314798 2010-11-09 00:32:54.868485
8   Bed_to_Toilet 2010-11-09 05:31:30.888221 2010-11-09 05:34:08.785188
9   Bed_to_Toilet 2010-11-11 05:13:58.821109 2010-11-11 05:16:28.261014
10  Bed_to_Toilet 2010-11-12 04:31:41.818859 2010-11-12 04:35:07.429031
11  Bed_to_Toilet 2010-11-13 05:17:05.045679 2010-11-13 05:20:52.478511
12  Bed_to_Toilet 2010-11-15 05:32:17.493645 2010-11-15 05:35:44.973115
13  Bed_to_Toilet 2010-11-16 00:37:28.060166 2010-11-16 00:39:25.601099
14  Bed_to_Toilet 2010-11-17 00:24:31.616930 2010-11-17 00:25:21.633567
15  Bed_to_Toilet 2010-11-17 02:58:56.283216 2010-11-17 03:01:58.145534
16  Bed_to_Toilet 2010-11-18 05:39:30.235604 2010-11-18 05:43:50.779600
17  Bed_to_Toilet 2010-11-20 00:36:14.715188 2010-11-20 00:37:05.903139
18  Bed_to_Toilet 2010-11-20 03:31:23.569485 2010-11-20 03:34:38.579317
19  Bed_to_Toilet 2010-11-21 00:17:52.486717 2010-11-21 00:21:09.771305
20  Bed_to_Toilet 2010-11-21 22:19:38.516703 2010-11-21 22:20:53.075808
21  Bed_to_Toilet 2010-11-22 05:44:20.244593 2010-11-22 05:47:35.208851
22  Bed_to_Toilet 2010-11-23 05:53:46.610096 2010-11-23 05:56:51.208908
23  Bed_to_Toilet 2010-11-24 00:37:30.531518 2010-11-24 00:40:06.451482
24  Bed_to_Toilet 2010-11-24 05:39:29.079102 2010-11-24 05:42:12.092995
25  Bed_to_Toilet 2010-11-25 00:48:28.990680 2010-11-25 00:51:35.047940
26  Bed_to_Toilet 2010-11-25 05:42:07.478061 2010-11-25 05:45:23.989755
27  Bed_to_Toilet 2010-11-26 05:51:54.349494 2010-11-26 05:55:29.629720
28  Bed_to_Toilet 2010-11-27 05:24:28.031033 2010-11-27 05:28:37.699942
29  Bed_to_Toilet 2010-11-27 23:44:41.585013 2010-11-27 23:45:51.790310
30  Bed_to_Toilet 2010-11-28 05:21:15.685275 2010-11-28 05:24:58.548113
31  Bed_to_Toilet 2010-11-29 01:38:51.469559 2010-11-29 01:39:31.011821
32  Bed_to_Toilet 2010-11-30 00:39:09.024296 2010-11-30 00:40:14.176605
33  Bed_to_Toilet 2010-11-30 06:03:43.446509 2010-11-30 06:06:26.452756
34  Bed_to_Toilet 2010-12-02 04:32:00.652119 2010-12-02 04:36:11.257836
35  Bed_to_Toilet 2010-12-03 00:40:01.592953 2010-12-03 00:42:32.452135
36  Bed_to_Toilet 2010-12-04 07:32:11.073465 2010-12-04 07:36:05.631460
37  Bed_to_Toilet 2010-12-04 22:59:25.891931 2010-12-04 23:01:10.902644
38  Bed_to_Toilet 2010-12-05 04:35:45.273022 2010-12-05 04:39:03.883315
39  Bed_to_Toilet 2010-12-06 04:19:01.362514 2010-12-06 04:22:01.392512
40  Bed_to_Toilet 2010-12-07 00:20:52.010563 2010-12-07 00:23:13.659864
41  Bed_to_Toilet 2010-12-07 05:15:20.582769 2010-12-07 05:17:52.033103
42  Bed_to_Toilet 2010-12-08 04:05:18.796797 2010-12-08 04:07:51.277149
43  Bed_to_Toilet 2010-12-09 03:09:22.532479 2010-12-09 03:12:24.654381
44  Bed_to_Toilet 2010-12-11 23:43:36.097306 2010-12-11 23:46:32.287586
45  Bed_to_Toilet 2010-12-12 03:47:32.464322 2010-12-12 03:50:36.912847
46  Bed_to_Toilet 2010-12-13 03:03:43.704985 2010-12-13 03:06:48.063366
47  Bed_to_Toilet 2010-12-14 06:20:16.680011 2010-12-14 06:23:38.649685
48  Bed_to_Toilet 2010-12-15 00:42:08.555409 2010-12-15 00:43:03.990217
49  Bed_to_Toilet 2010-12-15 05:13:10.475089 2010-12-15 05:16:21.351492

                 duration  duration_minutes        date  hour  minute  \
0  0 days 00:02:38.975282          2.649588  2010-11-04     5      40
1  0 days 00:02:40.703445          2.678391  2010-11-05     4      18
2  0 days 00:03:09.504772          3.158413  2010-11-06     4      23
3  0 days 00:00:47.351341          0.789189  2010-11-07     0      34
4  0 days 00:03:04.083794          3.068063  2010-11-07     3      43
5  0 days 00:01:57.316710          1.955278  2010-11-07     3      49
6  0 days 00:03:04.547225          3.075787  2010-11-08     5      40
7  0 days 00:02:22.553687          2.375895  2010-11-09     0      30
8  0 days 00:02:37.896967          2.631616  2010-11-09     5      31
9  0 days 00:02:29.439905          2.490665  2010-11-11     5      13
10 0 days 00:03:25.610172          3.426836  2010-11-12     4      31
11 0 days 00:03:47.432832          3.790547  2010-11-13     5      17
12 0 days 00:03:27.479470          3.457991  2010-11-15     5      32
13 0 days 00:01:57.540933          1.959016  2010-11-16     0      37
14 0 days 00:00:50.016637          0.833611  2010-11-17     0      24
15 0 days 00:03:01.862318          3.031039  2010-11-17     2      58
16 0 days 00:04:20.543996          4.342400  2010-11-18     5      39
17 0 days 00:00:51.187951          0.853133  2010-11-20     0      36
18 0 days 00:03:15.009832          3.250164  2010-11-20     3      31
19 0 days 00:03:17.284588          3.288076  2010-11-21     0      17
20 0 days 00:01:14.559105          1.242652  2010-11-21    22      19
21 0 days 00:03:14.964258          3.249404  2010-11-22     5      44
22 0 days 00:03:04.598812          3.076647  2010-11-23     5      53
23 0 days 00:02:35.919964          2.598666  2010-11-24     0      37
24 0 days 00:02:43.013893          2.716898  2010-11-24     5      39
25 0 days 00:03:06.057260          3.100954  2010-11-25     0      48
26 0 days 00:03:16.511694          3.275195  2010-11-25     5      42
27 0 days 00:03:35.280226          3.588004  2010-11-26     5      51
28 0 days 00:04:09.668909          4.161148  2010-11-27     5      24
29 0 days 00:01:10.205297          1.170088  2010-11-27    23      44
30 0 days 00:03:42.862838          3.714381  2010-11-28     5      21
31 0 days 00:00:39.542262          0.659038  2010-11-29     1      38
32 0 days 00:01:05.152309          1.085872  2010-11-30     0      39
33 0 days 00:02:43.006247          2.716771  2010-11-30     6       3
34 0 days 00:04:10.605717          4.176762  2010-12-02     4      32
35 0 days 00:02:30.859182          2.514320  2010-12-03     0      40
36 0 days 00:03:54.557995          3.909300  2010-12-04     7      32
37 0 days 00:01:45.010713          1.750179  2010-12-04    22      59
38 0 days 00:03:18.610293          3.310172  2010-12-05     4      35
39 0 days 00:03:00.029998          3.000500  2010-12-06     4      19
40 0 days 00:02:21.649301          2.360822  2010-12-07     0      20
41 0 days 00:02:31.450334          2.524172  2010-12-07     5      15
42 0 days 00:02:32.480352          2.541339  2010-12-08     4       5
43 0 days 00:03:02.121902          3.035365  2010-12-09     3       9
44 0 days 00:02:56.190280          2.936505  2010-12-11    23      43
45 0 days 00:03:04.448525          3.074142  2010-12-12     3      47
46 0 days 00:03:04.358381          3.072640  2010-12-13     3       3
47 0 days 00:03:21.969674          3.366161  2010-12-14     6      20
48 0 days 00:00:55.434808          0.923913  2010-12-15     0      42
49 0 days 00:03:10.876403          3.181273  2010-12-15     5      13

   day_of_week       start_time
0     Thursday  05:40:51.303739
1       Friday  04:18:09.406239
2     Saturday  04:23:50.544193
3       Sunday  00:34:48.871659
4       Sunday  03:43:19.802838
5       Sunday  03:49:20.647413
6       Monday  05:40:10.556874
7      Tuesday  00:30:32.314798
8      Tuesday  05:31:30.888221
9     Thursday  05:13:58.821109
10      Friday  04:31:41.818859
11    Saturday  05:17:05.045679
12      Monday  05:32:17.493645
13     Tuesday  00:37:28.060166
14   Wednesday  00:24:31.616930
15   Wednesday  02:58:56.283216
16    Thursday  05:39:30.235604
17    Saturday  00:36:14.715188
18    Saturday  03:31:23.569485
19      Sunday  00:17:52.486717
20      Sunday  22:19:38.516703
21      Monday  05:44:20.244593
22     Tuesday  05:53:46.610096
23   Wednesday  00:37:30.531518
24   Wednesday  05:39:29.079102
25    Thursday  00:48:28.990680
26    Thursday  05:42:07.478061
27      Friday  05:51:54.349494
28    Saturday  05:24:28.031033
29    Saturday  23:44:41.585013
30      Sunday  05:21:15.685275
31      Monday  01:38:51.469559
32     Tuesday  00:39:09.024296
33     Tuesday  06:03:43.446509
34    Thursday  04:32:00.652119
35      Friday  00:40:01.592953
36    Saturday  07:32:11.073465
37    Saturday  22:59:25.891931
38      Sunday  04:35:45.273022
39      Monday  04:19:01.362514
40     Tuesday  00:20:52.010563
41     Tuesday  05:15:20.582769
42   Wednesday  04:05:18.796797
43    Thursday  03:09:22.532479
44    Saturday  23:43:36.097306
45      Sunday  03:47:32.464322
46      Monday  03:03:43.704985
47     Tuesday  06:20:16.680011
48   Wednesday  00:42:08.555409
49   Wednesday  05:13:10.475089

In [ ]:
routine_summary = (
    activity_duration_df
    .groupby("activity")
    .agg(
        average_start_hour=("hour", "mean"),
        average_duration=("duration_minutes", "mean"),
        min_duration=("duration_minutes", "min"),
        max_duration=("duration_minutes", "max"),
        frequency=("activity", "count") #el frequency of each activity yaane kam event et3ml w kheles completed
    )
    .reset_index()
)

print(routine_summary)

            activity  average_start_hour  average_duration  min_duration  \
0      Bed_to_Toilet            4.192308          2.729481      0.357222
1   CLOSE Enter_Home           20.000000        829.721475    829.721475
2   CLOSE Leave_Home            8.000000        431.749579    431.749579
3             Eating           12.670588         10.149268      0.264641
4         Enter_Home           14.000000        391.872700    391.872700
5       Housekeeping           12.575758         20.324018      1.536077
6         Leave_Home           13.500000       7846.165769      0.014001
7   Meal_Preparation           12.578056          7.838226      0.126168
8              Relax           15.271851         33.431752      0.944290
9          Respirate           11.166667          8.564308      1.638024
10          Sleeping            8.801008        241.214425      0.555374
11       Wash_Dishes           14.937500          7.246125      0.554909
12              Work           12.935673         17.080463      0.913070

    max_duration  frequency
0       8.702630        156
1     829.721475          1
2     431.749579          1
3      69.475333        255
4     391.872700          1
5      90.010639         33
6   15692.317537          2
7     326.200545       1595
8     255.024874       2906
9      24.919531          6
10    646.396949        397
11     36.654173         64
12    116.940938        171

In [18]:
routine_data = activity_duration_df[
    [
        "date",
        "activity",
        "start",
        "duration_minutes",
        "day_of_week"
    ]
].copy()

print(routine_data.head())

         date       activity                      start  duration_minutes  \
0  2010-11-04  Bed_to_Toilet 2010-11-04 05:40:51.303739          2.649588
1  2010-11-05  Bed_to_Toilet 2010-11-05 04:18:09.406239          2.678391
2  2010-11-06  Bed_to_Toilet 2010-11-06 04:23:50.544193          3.158413
3  2010-11-07  Bed_to_Toilet 2010-11-07 00:34:48.871659          0.789189
4  2010-11-07  Bed_to_Toilet 2010-11-07 03:43:19.802838          3.068063

  day_of_week
0    Thursday
1      Friday
2    Saturday
3      Sunday
4      Sunday

In [27]:
daily_frequency = (
    routine_data
    .groupby(["date", "activity"])
    .size()
    .reset_index(name="count")
)

print(daily_frequency.tail())

            date          activity  count
1088  2011-06-10              Work      1
1089  2011-06-11            Eating      1
1090  2011-06-11  Meal_Preparation      8
1091  2011-06-11             Relax     17
1092  2011-06-11              Work      1

In [28]:
average_frequency = (
    daily_frequency
    .groupby("activity")["count"]
    .mean()
    .reset_index(name="average_daily_frequency")
)

print(average_frequency)

            activity  average_daily_frequency
0      Bed_to_Toilet                 1.172932
1   CLOSE Enter_Home                 1.000000
2   CLOSE Leave_Home                 1.000000
3             Eating                 1.861314
4         Enter_Home                 1.000000
5       Housekeeping                 1.178571
6         Leave_Home                 1.000000
7   Meal_Preparation                 7.283105
8              Relax                13.269406
9          Respirate                 1.000000
10          Sleeping                 1.965347
11       Wash_Dishes                 1.254902
12              Work                 1.838710

In [29]:
activities_to_remove = [
    "CLOSE Enter_Home",
    "CLOSE Leave_Home",
    "OPEN Enter_Home",
    "OPEN Leave_Home",
    "Enter_Home",
    "Leave_Home",
    "Respirate"
] #shelna el door activities for now

df = df[~df["activity_label"].isin(activities_to_remove)].copy()

print(df["activity_label"].value_counts())

activity_label
Relax               5837
Meal_Preparation    3211
Sleeping             801
Eating               514
Work                 342
Bed_to_Toilet        314
Wash_Dishes          130
Housekeeping          66
Name: count, dtype: int64

In [31]:
# Activities we don't want in the routine baseline
activities_to_remove = [
    "CLOSE Enter_Home",
    "CLOSE Leave_Home",
    "OPEN Enter_Home",
    "OPEN Leave_Home",
    "Enter_Home",
    "Leave_Home",
    "Respirate"
]

# Remove them from df
df = df[~df["activity_label"].isin(activities_to_remove)].copy()


# =========================================
# Recreate activity_duration_df
# =========================================

df["timestamp"] = pd.to_datetime(df["timestamp"])

activity_df = df[df["activity_label"].notna()].copy()
activity_df = activity_df.sort_values("timestamp")

activities = []

for activity, group in activity_df.groupby("activity_label"):

    group = group.sort_values("timestamp")
    start_time = None

    for _, row in group.iterrows():

        if row["activity_state"] == "begin":
            start_time = row["timestamp"]

        elif row["activity_state"] == "end" and start_time is not None:

            end_time = row["timestamp"]

            activities.append({
                "activity": activity,
                "start": start_time,
                "end": end_time,
                "duration": end_time - start_time
            })

            start_time = None


activity_duration_df = pd.DataFrame(activities)

# Duration in minutes
activity_duration_df["duration_minutes"] = (
    activity_duration_df["duration"].dt.total_seconds() / 60
)

# Add time features
activity_duration_df["date"] = activity_duration_df["start"].dt.date
activity_duration_df["hour"] = activity_duration_df["start"].dt.hour
activity_duration_df["minute"] = activity_duration_df["start"].dt.minute

In [ ]:
#baseline table
daily_frequency = (
    activity_duration_df
    .groupby(["date", "activity"])
    .size()
    .reset_index(name="daily_frequency")
)

average_frequency = (
    daily_frequency
    .groupby("activity")["daily_frequency"]
    .mean()
    .reset_index(name="average_daily_frequency")
)

duration_stats = (
    activity_duration_df
    .groupby("activity")
    .agg(
        average_duration=("duration_minutes", "mean"),
        min_duration=("duration_minutes", "min"),
        max_duration=("duration_minutes", "max"),
        average_start_hour=("hour", "mean")
    )
    .reset_index()
)

baseline_table = average_frequency.merge(
    duration_stats,
    on="activity"
)

baseline_table = baseline_table.round(2)

print(baseline_table)

           activity  average_daily_frequency  average_duration  min_duration  \
0     Bed_to_Toilet                     1.17              2.73          0.36
1            Eating                     1.86             10.15          0.26
2      Housekeeping                     1.18             20.32          1.54
3  Meal_Preparation                     7.28              7.84          0.13
4             Relax                    13.27             33.43          0.94
5          Sleeping                     1.97            241.21          0.56
6       Wash_Dishes                     1.25              7.25          0.55
7              Work                     1.84             17.08          0.91

   max_duration  average_start_hour
0          8.70                4.19
1         69.48               12.67
2         90.01               12.58
3        326.20               12.58
4        255.02               15.27
5        646.40                8.80
6         36.65               14.94
7        116.94               12.94

In [ ]:
# =========================================
# Daily Routine Table
# =========================================
#What is normal for this person overall


daily_routine = (
    activity_duration_df
    .groupby(["date", "activity"])
    .agg(
        frequency=("activity", "count"),
        total_duration=("duration_minutes", "sum"),
        average_duration=("duration_minutes", "mean"),
        average_start_hour=("hour", "mean")
    )
    .reset_index()
)

# Round the numbers
daily_routine = daily_routine.round(2)

print(daily_routine.head(20))

          date          activity  frequency  total_duration  average_duration  \
0   2010-11-04     Bed_to_Toilet          1            2.65              2.65
1   2010-11-04            Eating          4           10.44              2.61
2   2010-11-04      Housekeeping          2           15.06              7.53
3   2010-11-04  Meal_Preparation          9           67.29              7.48
4   2010-11-04             Relax          5           64.01             12.80
5   2010-11-04          Sleeping          2          474.33            237.17
6   2010-11-04       Wash_Dishes          2           19.00              9.50
7   2010-11-04              Work          2           25.13             12.57
8   2010-11-05     Bed_to_Toilet          1            2.68              2.68
9   2010-11-05            Eating          1            3.50              3.50
10  2010-11-05      Housekeeping          1           90.01             90.01
11  2010-11-05  Meal_Preparation          3            8.02              2.67
12  2010-11-05             Relax          2            9.76              4.88
13  2010-11-05          Sleeping          3          800.32            266.77
14  2010-11-05       Wash_Dishes          1            0.84              0.84
15  2010-11-05              Work          7           62.13              8.88
16  2010-11-06     Bed_to_Toilet          1            3.16              3.16
17  2010-11-06            Eating          3           29.92              9.97
18  2010-11-06      Housekeeping          2           56.98             28.49
19  2010-11-06  Meal_Preparation          4           21.50              5.37

    average_start_hour
0                 5.00
1                12.50
2                10.00
3                12.67
4                14.60
5                 2.50
6                13.50
7                16.00
8                 4.00
9                16.00
10                9.00
11               13.00
12               11.00
13                8.67
14               16.00
15               10.86
16                4.00
17               11.00
18               10.50
19               10.00

In [38]:
# =========================================
# Compare daily routine with baseline
# =========================================

routine_comparison = daily_routine.merge(
    baseline_table,
    on="activity",
    suffixes=("_daily", "_baseline")
)

print(routine_comparison.head(20))

          date          activity  frequency  total_duration  \
0   2010-11-04     Bed_to_Toilet          1            2.65
1   2010-11-04            Eating          4           10.44
2   2010-11-04      Housekeeping          2           15.06
3   2010-11-04  Meal_Preparation          9           67.29
4   2010-11-04             Relax          5           64.01
5   2010-11-04          Sleeping          2          474.33
6   2010-11-04       Wash_Dishes          2           19.00
7   2010-11-04              Work          2           25.13
8   2010-11-05     Bed_to_Toilet          1            2.68
9   2010-11-05            Eating          1            3.50
10  2010-11-05      Housekeeping          1           90.01
11  2010-11-05  Meal_Preparation          3            8.02
12  2010-11-05             Relax          2            9.76
13  2010-11-05          Sleeping          3          800.32
14  2010-11-05       Wash_Dishes          1            0.84
15  2010-11-05              Work          7           62.13
16  2010-11-06     Bed_to_Toilet          1            3.16
17  2010-11-06            Eating          3           29.92
18  2010-11-06      Housekeeping          2           56.98
19  2010-11-06  Meal_Preparation          4           21.50

    average_duration_daily  average_start_hour_daily  average_daily_frequency  \
0                     2.65                      5.00                     1.17
1                     2.61                     12.50                     1.86
2                     7.53                     10.00                     1.18
3                     7.48                     12.67                     7.28
4                    12.80                     14.60                    13.27
5                   237.17                      2.50                     1.97
6                     9.50                     13.50                     1.25
7                    12.57                     16.00                     1.84
8                     2.68                      4.00                     1.17
9                     3.50                     16.00                     1.86
10                   90.01                      9.00                     1.18
11                    2.67                     13.00                     7.28
12                    4.88                     11.00                    13.27
13                  266.77                      8.67                     1.97
14                    0.84                     16.00                     1.25
15                    8.88                     10.86                     1.84
16                    3.16                      4.00                     1.17
17                    9.97                     11.00                     1.86
18                   28.49                     10.50                     1.18
19                    5.37                     10.00                     7.28

    average_duration_baseline  min_duration  max_duration  \
0                        2.73          0.36          8.70
1                       10.15          0.26         69.48
2                       20.32          1.54         90.01
3                        7.84          0.13        326.20
4                       33.43          0.94        255.02
5                      241.21          0.56        646.40
6                        7.25          0.55         36.65
7                       17.08          0.91        116.94
8                        2.73          0.36          8.70
9                       10.15          0.26         69.48
10                      20.32          1.54         90.01
11                       7.84          0.13        326.20
12                      33.43          0.94        255.02
13                     241.21          0.56        646.40
14                       7.25          0.55         36.65
15                      17.08          0.91        116.94
16                       2.73          0.36          8.70
17                      10.15          0.26         69.48
18                      20.32          1.54         90.01
19                       7.84          0.13        326.20

    average_start_hour_baseline
0                          4.19
1                         12.67
2                         12.58
3                         12.58
4                         15.27
5                          8.80
6                         14.94
7                         12.94
8                          4.19
9                         12.67
10                        12.58
11                        12.58
12                        15.27
13                         8.80
14                        14.94
15                        12.94
16                         4.19
17                        12.67
18                        12.58
19                        12.58

In [35]:
# Frequency deviation
routine_comparison["frequency_deviation"] = (
    routine_comparison["frequency"]
    - routine_comparison["average_daily_frequency"]
)

# Duration deviation
routine_comparison["duration_deviation"] = (
    routine_comparison["average_duration_daily"]
    - routine_comparison["average_duration_baseline"]
)

# Start-time deviation
routine_comparison["start_time_deviation"] = (
    routine_comparison["average_start_hour_daily"]
    - routine_comparison["average_start_hour_baseline"]
)

# Round the results
routine_comparison[
    [
        "frequency_deviation",
        "duration_deviation",
        "start_time_deviation"
    ]
] = routine_comparison[
    [
        "frequency_deviation",
        "duration_deviation",
        "start_time_deviation"
    ]
].round(2)

print(routine_comparison.head(20))

          date          activity  frequency  total_duration  \
0   2010-11-04     Bed_to_Toilet          1            2.65
1   2010-11-04            Eating          4           10.44
2   2010-11-04      Housekeeping          2           15.06
3   2010-11-04  Meal_Preparation          9           67.29
4   2010-11-04             Relax          5           64.01
5   2010-11-04          Sleeping          2          474.33
6   2010-11-04       Wash_Dishes          2           19.00
7   2010-11-04              Work          2           25.13
8   2010-11-05     Bed_to_Toilet          1            2.68
9   2010-11-05            Eating          1            3.50
10  2010-11-05      Housekeeping          1           90.01
11  2010-11-05  Meal_Preparation          3            8.02
12  2010-11-05             Relax          2            9.76
13  2010-11-05          Sleeping          3          800.32
14  2010-11-05       Wash_Dishes          1            0.84
15  2010-11-05              Work          7           62.13
16  2010-11-06     Bed_to_Toilet          1            3.16
17  2010-11-06            Eating          3           29.92
18  2010-11-06      Housekeeping          2           56.98
19  2010-11-06  Meal_Preparation          4           21.50

    average_duration_daily  average_start_hour_daily  average_daily_frequency  \
0                     2.65                      5.00                     1.17
1                     2.61                     12.50                     1.86
2                     7.53                     10.00                     1.18
3                     7.48                     12.67                     7.28
4                    12.80                     14.60                    13.27
5                   237.17                      2.50                     1.97
6                     9.50                     13.50                     1.25
7                    12.57                     16.00                     1.84
8                     2.68                      4.00                     1.17
9                     3.50                     16.00                     1.86
10                   90.01                      9.00                     1.18
11                    2.67                     13.00                     7.28
12                    4.88                     11.00                    13.27
13                  266.77                      8.67                     1.97
14                    0.84                     16.00                     1.25
15                    8.88                     10.86                     1.84
16                    3.16                      4.00                     1.17
17                    9.97                     11.00                     1.86
18                   28.49                     10.50                     1.18
19                    5.37                     10.00                     7.28

    average_duration_baseline  min_duration  max_duration  \
0                        2.73          0.36          8.70
1                       10.15          0.26         69.48
2                       20.32          1.54         90.01
3                        7.84          0.13        326.20
4                       33.43          0.94        255.02
5                      241.21          0.56        646.40
6                        7.25          0.55         36.65
7                       17.08          0.91        116.94
8                        2.73          0.36          8.70
9                       10.15          0.26         69.48
10                      20.32          1.54         90.01
11                       7.84          0.13        326.20
12                      33.43          0.94        255.02
13                     241.21          0.56        646.40
14                       7.25          0.55         36.65
15                      17.08          0.91        116.94
16                       2.73          0.36          8.70
17                      10.15          0.26         69.48
18                      20.32          1.54         90.01
19                       7.84          0.13        326.20

    average_start_hour_baseline  frequency_deviation  duration_deviation  \
0                          4.19                -0.17               -0.08
1                         12.67                 2.14               -7.54
2                         12.58                 0.82              -12.79
3                         12.58                 1.72               -0.36
4                         15.27                -8.27              -20.63
5                          8.80                 0.03               -4.04
6                         14.94                 0.75                2.25
7                         12.94                 0.16               -4.51
8                          4.19                -0.17               -0.05
9                         12.67                -0.86               -6.65
10                        12.58                -0.18               69.69
11                        12.58                -4.28               -5.17
12                        15.27               -11.27              -28.55
13                         8.80                 1.03               25.56
14                        14.94                -0.25               -6.41
15                        12.94                 5.16               -8.20
16                         4.19                -0.17                0.43
17                        12.67                 1.14               -0.18
18                        12.58                 0.82                8.17
19                        12.58                -3.28               -2.47

    start_time_deviation
0                   0.81
1                  -0.17
2                  -2.58
3                   0.09
4                  -0.67
5                  -6.30
6                  -1.44
7                   3.06
8                  -0.19
9                   3.33
10                 -3.58
11                  0.42
12                 -4.27
13                 -0.13
14                  1.06
15                 -2.08
16                 -0.19
17                 -1.67
18                 -2.08
19                 -2.58

KeyError: 'frequency_deviation'

In [40]:
routine_comparison = daily_routine.merge(
    baseline_table,
    on="activity",
    suffixes=("_daily", "_baseline")
)

routine_comparison["frequency_deviation"] = (
    routine_comparison["frequency"]
    - routine_comparison["average_daily_frequency"]
)

routine_comparison["duration_deviation"] = (
    routine_comparison["average_duration_daily"]
    - routine_comparison["average_duration_baseline"]
)

routine_comparison["start_time_deviation"] = (
    routine_comparison["average_start_hour_daily"]
    - routine_comparison["average_start_hour_baseline"]
)

In [41]:
routine_comparison.columns

Index(['date', 'activity', 'frequency', 'total_duration',
       'average_duration_daily', 'average_start_hour_daily',
       'average_daily_frequency', 'average_duration_baseline', 'min_duration',
       'max_duration', 'average_start_hour_baseline', 'frequency_deviation',
       'duration_deviation', 'start_time_deviation'],
      dtype='object')

In [42]:
variability = (
    daily_routine
    .groupby("activity")
    .agg(
        frequency_std=("frequency", "std"),
        duration_std=("average_duration", "std"),
        start_time_std=("average_start_hour", "std")
    )
    .reset_index()
)

variability

           activity  frequency_std  duration_std  start_time_std
0     Bed_to_Toilet       0.435390      0.985498        2.613255
1            Eating       1.356805      7.713036        3.528412
2      Housekeeping       0.390021     20.218954        2.987186
3  Meal_Preparation       3.554586      4.260761        2.147345
4             Relax       4.000634     11.306951        1.645044
5          Sleeping       0.883113    100.152102        6.712690
6       Wash_Dishes       0.483452      7.489216        4.328433
7              Work       1.236143     18.356466        3.579488

In [43]:
routine_comparison = routine_comparison.merge(
    variability,
    on="activity",
    how="left"
)

In [44]:
import numpy as np

routine_comparison["frequency_deviation_score"] = (
    routine_comparison["frequency_deviation"].abs()
    / routine_comparison["frequency_std"]
)

routine_comparison["duration_deviation_score"] = (
    routine_comparison["duration_deviation"].abs()
    / routine_comparison["duration_std"]
)

routine_comparison["start_time_deviation_score"] = (
    routine_comparison["start_time_deviation"].abs()
    / routine_comparison["start_time_std"]
)

In [45]:
score_columns = [
    "frequency_deviation_score",
    "duration_deviation_score",
    "start_time_deviation_score"
]

routine_comparison[score_columns] = (
    routine_comparison[score_columns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
    .round(2)
)

In [46]:
routine_comparison[
    [
        "date",
        "activity",
        "frequency_deviation_score",
        "duration_deviation_score",
        "start_time_deviation_score"
    ]
].head(20)

,date,activity,frequency_deviation_score,duration_deviation_score,start_time_deviation_score
0,2010-11-04,Bed_to_Toilet,0.39,0.08,0.31
1,2010-11-04,Eating,1.58,0.98,0.05
2,2010-11-04,Housekeeping,2.10,0.63,0.86
3,2010-11-04,Meal_Preparation,0.48,0.08,0.04
4,2010-11-04,Relax,2.07,1.82,0.41
5,2010-11-04,Sleeping,0.03,0.04,0.94
6,2010-11-04,Wash_Dishes,1.55,0.30,0.33
7,2010-11-04,Work,0.13,0.25,0.85
8,2010-11-05,Bed_to_Toilet,0.39,0.05,0.07
9,2010-11-05,Eating,0.63,0.86,0.94
10,2010-11-05,Housekeeping,0.46,3.45,1.20
11,2010-11-05,Meal_Preparation,1.20,1.21,0.20
12,2010-11-05,Relax,2.82,2.52,2.60
13,2010-11-05,Sleeping,1.17,0.26,0.02
14,2010-11-05,Wash_Dishes,0.52,0.86,0.24
15,2010-11-05,Work,4.17,0.45,0.58
16,2010-11-06,Bed_to_Toilet,0.39,0.44,0.07
17,2010-11-06,Eating,0.84,0.02,0.47
18,2010-11-06,Housekeeping,2.10,0.40,0.70
19,2010-11-06,Meal_Preparation,0.92,0.58,1.20